// Command dev-install creates "<tool>-dev" launchers that always run the
// rigsmith tools from your working tree (via `go run`), independent of whatever
// stable rig/relrig/clauderig you have installed globally.
//
// It is cross-platform: on macOS/Linux it writes POSIX `sh` wrappers, on Windows
// it writes `.cmd` wrappers. It discovers the tools from go.work, so adding a new
// module to the workspace makes a new `<tool>-dev` appear here automatically.
//
//	go run ./scripts/dev-install            # install (or refresh) the wrappers
//	RIGSMITH_DEV_BIN=/some/dir go run ./scripts/dev-install
//
// Each wrapper runs `go run -C <repo> ./<module>`, so it compiles your current
// source on every invocation (Go's build cache keeps that fast) — edits take
// effect on the next run with no reinstall.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"runtime"
	"strings"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "dev-install:", err)
		os.Exit(1)
	}
}

func run() error {
	repo, err := findRepoRoot()
	if err != nil {
		return err
	}
	modules, err := workspaceModules(repo)
	if err != nil {
		return err
	}

	bin := installDir()
	if err := os.MkdirAll(bin, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", bin, err)
	}

	var made []string
	for _, mod := range modules {
		name := commandName(filepath.Join(repo, mod))
		if name == "" {
			continue // library module (no main package) — nothing to launch
		}
		path, err := writeWrapper(bin, name, repo, mod)
		if err != nil {
			return err
		}
		made = append(made, fmt.Sprintf("  %-16s -> go run -C %s ./%s", filepath.Base(path), repo, mod))
	}

	if len(made) == 0 {
		return fmt.Errorf("no runnable tools found in %s/go.work", repo)
	}
	fmt.Printf("Installed %d dev launcher(s) in %s:\n", len(made), bin)
	fmt.Println(strings.Join(made, "\n"))
	printPathHint(bin)
	return nil
}

// findRepoRoot walks up from the working directory to the dir containing go.work.
func findRepoRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.work")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("no go.work found above the current directory; run this from inside the rigsmith repo")
		}
		dir = parent
	}
}

var useEntry = regexp.MustCompile(`(?m)^\s*(?:use\s+)?(\./[^\s()]+)`)

// workspaceModules returns the module directories listed in go.work's use block,
// as repo-relative slash paths (e.g. "cli", "release").
func workspaceModules(repo string) ([]string, error) {
	data, err := os.ReadFile(filepath.Join(repo, "go.work"))
	if err != nil {
		return nil, err
	}
	var mods []string
	for _, m := range useEntry.FindAllStringSubmatch(string(data), -1) {
		mod := strings.TrimPrefix(filepath.ToSlash(m[1]), "./")
		if mod == "scripts/dev-install" {
			continue // don't make a launcher for the installer itself
		}
		mods = append(mods, mod)
	}
	return mods, nil
}

var commandDoc = regexp.MustCompile(`(?m)^// Command (\S+)`)

// commandName reads "// Command <name>" from the module's main.go. Returns ""
// when the module has no main.go (a library).
func commandName(moduleDir string) string {
	data, err := os.ReadFile(filepath.Join(moduleDir, "main.go"))
	if err != nil {
		return ""
	}
	if m := commandDoc.FindStringSubmatch(string(data)); m != nil {
		return m[1]
	}
	return ""
}

func installDir() string {
	if dir := os.Getenv("RIGSMITH_DEV_BIN"); dir != "" {
		return dir
	}
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".local", "bin")
}

// writeWrapper writes the launcher for one tool and returns its path.
func writeWrapper(bin, name, repo, mod string) (string, error) {
	var path, body string
	if runtime.GOOS == "windows" {
		path = filepath.Join(bin, name+"-dev.cmd")
		body = fmt.Sprintf("@echo off\r\n"+
			"rem rigsmith dev launcher for %s — runs live source from the working tree.\r\n"+
			"rem Generated by scripts/dev-install; re-run it to refresh.\r\n"+
			"go run -C \"%s\" ./%s %%*\r\n", name, repo, mod)
	} else {
		path = filepath.Join(bin, name+"-dev")
		body = fmt.Sprintf("#!/bin/sh\n"+
			"# rigsmith dev launcher for %s — runs live source from the working tree.\n"+
			"# Generated by scripts/dev-install; re-run it to refresh.\n"+
			"exec go run -C \"%s\" ./%s \"$@\"\n", name, repo, mod)
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return "", fmt.Errorf("writing %s: %w", path, err)
	}
	return path, nil
}

func printPathHint(bin string) {
	for _, p := range filepath.SplitList(os.Getenv("PATH")) {
		if p == bin {
			return // already on PATH
		}
	}
	fmt.Printf("\nNote: %s is not on your PATH. Add it:\n", bin)
	if runtime.GOOS == "windows" {
		fmt.Printf("  setx PATH \"%%PATH%%;%s\"\n", bin)
	} else {
		fmt.Printf("  export PATH=\"%s:$PATH\"   # add to ~/.zshrc or ~/.bashrc\n", bin)
	}
}
