// Command dev-install creates "<tool>-dev" and "<tool>-wt" launchers that run
// the rigsmith tools from your working tree, independent of whatever stable
// rig/shiprig/clauderig you have installed globally.
//
// It is cross-platform: on macOS/Linux it writes POSIX `sh` wrappers, on Windows
// it writes `.cmd` wrappers. It discovers the tools from go.work, so adding a new
// module to the workspace makes new `<tool>-dev`/`<tool>-wt` launchers appear
// here automatically.
//
//	go run ./scripts/dev-install            # install (or refresh) the wrappers
//	RIGSMITH_DEV_BIN=/some/dir go run ./scripts/dev-install
//
// Each `-dev` wrapper *builds* <module> from the repo (Go's build cache keeps
// that fast) to a temp binary and then execs it from YOUR current directory — so
// the tool resolves the workspace where you actually are, not the repo. (`go run
// -C <repo>` would reset the working directory to the repo, making every command
// operate on rigsmith no matter where you ran it.) Edits take effect on the next
// run with no reinstall.
//
// The build source defaults to this repo but is overridable per invocation via
// RIGSMITH_DEV_SRC, so you can test a feature living in a git worktree from any
// other repo. Because every tool shares one workspace, the override is repo-level
// and a single env var spans all tools:
//
//	RIGSMITH_DEV_SRC=/path/to/worktree rig-dev …   # build that tree, run from cwd
//
// The `-wt` wrappers wrap that: `<tool>-wt [query] [args]` resolves a git
// worktree and runs that tree's <tool> from your cwd, printing what it resolved
// to. A query fuzzy-matches a worktree (exact > prefix > substring >
// subsequence) — e.g. `rig-wt gowat doctor` — and runs it (resolution lives in
// `clauderig worktree pick`, sharing core/match). With NO query it opens an
// interactive menu (`clauderig worktree menu`): arrow to a worktree and run it,
// or pin/unpin it as the -dev route (below). Per-source builds go to separate
// temp dirs so the main tree and a worktree never clobber each other's binary.
//
// `<tool>-wt --use [query]` goes a step further and *pins* the resolved worktree
// as the repo's active route (`clauderig worktree use`), so a bare `<tool>-dev`
// builds from it without repeating the selection; `<tool>-wt --unset` clears it.
// The pin is a per-repo file (see core/devroute) that the `-dev` wrappers read.
// Build-source precedence is RIGSMITH_DEV_SRC env > pinned route > this repo, so
// a one-off env override or a transient `<tool>-wt [query]` still wins without
// unpinning.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/rigsmith/core/devroute"
	"github.com/rigsmith/core/gowork"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "dev-install:", err)
		os.Exit(1)
	}
}

func run() error {
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}
	repo, err := gowork.FindRoot(cwd)
	if err != nil {
		return err
	}
	tools, err := gowork.Tools(repo)
	if err != nil {
		return err
	}

	bin := installDir()
	if err := os.MkdirAll(bin, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", bin, err)
	}

	var made []string
	for _, t := range tools {
		if strings.HasPrefix(t.Module, "scripts/") {
			continue // installers (scripts/*) don't get their own launchers
		}
		devPath, wtPath, err := writeWrapper(bin, t.Name, repo, t.Module)
		if err != nil {
			return err
		}
		made = append(made,
			fmt.Sprintf("  %-18s build %s from cwd (RIGSMITH_DEV_SRC or pinned route, else repo)", filepath.Base(devPath), t.Name),
			fmt.Sprintf("  %-18s run a worktree's %s; --use [query] pins it as the -dev route", filepath.Base(wtPath), t.Name),
		)
	}

	if len(made) == 0 {
		return fmt.Errorf("no runnable tools found in %s/go.work", repo)
	}
	fmt.Printf("Installed %d dev launcher(s) in %s:\n", len(made), bin)
	fmt.Println(strings.Join(made, "\n"))
	printPathHint(bin)
	return nil
}

func installDir() string {
	if dir := os.Getenv("RIGSMITH_DEV_BIN"); dir != "" {
		return dir
	}
	home, err := os.UserHomeDir()
	if err != nil {
		home = "."
	}
	return filepath.Join(home, ".local", "bin")
}

// Launcher templates. Placeholders ({{NAME}}, {{REPO}}, {{MOD}}, {{DEV}},
// {{PICKER}}) are substituted by writeLauncher; on Windows it also rewrites \n
// to \r\n. Using raw literals keeps the shell/batch readable (no %%-escaping)
// and the `%` in the .cmd files literal.
const (
	devWrapperSh = `#!/bin/sh
# rigsmith dev launcher for {{NAME}} — builds live source from the working tree
# and runs it from YOUR current directory. Generated by scripts/dev-install.
# Build source: RIGSMITH_DEV_SRC env > pinned route ({{NAME}}-wt --use) > this
# repo. An explicit env var is used verbatim — a bad path fails the build, which
# surfaces the typo; only a pinned route whose worktree was removed falls back to
# the repo. (go run -C would reset cwd to the repo, resolving the wrong workspace.)
set -e
src="${RIGSMITH_DEV_SRC:-}"
if [ -z "$src" ] && [ -f "{{ROUTE}}" ]; then
	src="$(cat "{{ROUTE}}")"
	if [ -n "$src" ] && [ ! -d "$src" ]; then
		echo "{{NAME}}-dev: pinned route $src is gone — using repo" >&2
		src=""
	fi
fi
src="${src:-{{REPO}}}"
slug="$(printf %s "$src" | tr -c 'A-Za-z0-9' _)"
dir="${TMPDIR:-/tmp}/rigsmith-dev/$slug"
mkdir -p "$dir"
go build -C "$src" -o "$dir/{{NAME}}" "./{{MOD}}"
exec "$dir/{{NAME}}" "$@"
`

	wtWrapperSh = `#!/bin/sh
# rigsmith worktree launcher for {{NAME}} — runs a git worktree's source from
# YOUR current directory. Generated by scripts/dev-install.
# Usage: {{NAME}}-wt [<query|branch|path>] [args...]
#   query   fuzzy-matches a worktree (exact > prefix > substring > subsequence).
#   no query opens an interactive menu: run a worktree, or pin/unpin it as the
#           -dev route; use a lone "--" to pass only tool args without a query.
#   --use [query]  pin the resolved worktree as the active route for the -dev
#                  tools (then a bare {{NAME}}-dev builds from it); --unset clears.
set -e
case "${1:-}" in
	-h|--help)
		echo "usage: {{NAME}}-wt [<query|branch|path>] [args...]" >&2
		echo "       {{NAME}}-wt                   open the worktree menu (run / pin / unpin)" >&2
		echo "       {{NAME}}-wt --use [<query>]   pin a worktree as the active -dev route" >&2
		echo "       {{NAME}}-wt --unset           clear the pinned route" >&2
		echo "  query fuzzy-matches a worktree and runs it" >&2
		exit 0
		;;
	-u|--use)
		shift
		if [ "$#" -gt 0 ]; then
			exec "{{PICKER}}" worktree use --repo "{{REPO}}" -- "$1"
		fi
		exec "{{PICKER}}" worktree use --repo "{{REPO}}"
		;;
	--unset|--off)
		exec "{{PICKER}}" worktree unset --repo "{{REPO}}"
		;;
esac
query=""
if [ "${1:-}" = "--" ]; then
	shift
elif [ "$#" -gt 0 ]; then
	query="$1"
	shift
fi
if [ -n "$query" ]; then
	src="$("{{PICKER}}" worktree pick --repo "{{REPO}}" -- "$query")" || exit $?
else
	# No query: an interactive menu — run a worktree, or pin/unpin the -dev route.
	# It prints a path only when you choose "run"; pin/unpin/cancel print nothing,
	# so there's nothing left to run.
	src="$("{{PICKER}}" worktree menu --repo "{{REPO}}")" || exit $?
	[ -z "$src" ] && exit 0
fi
branch="$(git -C "$src" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
echo "{{NAME}}-wt → {{NAME}} $* @ $branch  ($src)" >&2
exec env RIGSMITH_DEV_SRC="$src" "{{DEV}}" "$@"
`

	devWrapperCmd = `@echo off
rem rigsmith dev launcher for {{NAME}} — builds live source from the working tree
rem and runs it from YOUR current directory. Generated by scripts/dev-install.
rem Build source: RIGSMITH_DEV_SRC env > pinned route ({{NAME}}-wt --use) > repo.
rem An explicit env var is used verbatim (a bad path fails the build); only a
rem pinned route whose worktree was removed falls back to the repo.
setlocal
set "SRC=%RIGSMITH_DEV_SRC%"
if defined SRC goto :gotsrc
if not exist "{{ROUTE}}" goto :userepo
set /p SRC=<"{{ROUTE}}"
if not defined SRC goto :userepo
if exist "%SRC%\" goto :gotsrc
echo {{NAME}}-dev: pinned route %SRC% is gone — using repo>&2
:userepo
set "SRC={{REPO}}"
:gotsrc
set "SLUG=%SRC%"
set "SLUG=%SLUG::=_%"
set "SLUG=%SLUG:\=_%"
set "SLUG=%SLUG:/=_%"
set "SLUG=%SLUG: =_%"
set "RIGDEVDIR=%TEMP%\rigsmith-dev\%SLUG%"
if not exist "%RIGDEVDIR%" mkdir "%RIGDEVDIR%"
go build -C "%SRC%" -o "%RIGDEVDIR%\{{NAME}}.exe" "./{{MOD}}" || exit /b %ERRORLEVEL%
"%RIGDEVDIR%\{{NAME}}.exe" %*
`

	wtWrapperCmd = `@echo off
rem rigsmith worktree launcher for {{NAME}} — runs a git worktree's source from
rem YOUR current directory. Generated by scripts/dev-install.
rem Usage: {{NAME}}-wt [^<query^|branch^|path^>] [args...]
rem   query fuzzy-matches a worktree; no query opens an interactive menu.
rem   --use [query] pins the resolved worktree as the active -dev route; --unset clears.
setlocal enabledelayedexpansion
if "%~1"=="-u"      goto :pin
if "%~1"=="--use"   goto :pin
if "%~1"=="--unset" goto :unpin
if "%~1"=="--off"   goto :unpin
goto :run

:pin
if not "%~2"=="" (
	"{{PICKER}}" worktree use --repo "{{REPO}}" -- "%~2"
) else (
	"{{PICKER}}" worktree use --repo "{{REPO}}"
)
exit /b %ERRORLEVEL%

:unpin
"{{PICKER}}" worktree unset --repo "{{REPO}}"
exit /b %ERRORLEVEL%

:run
set "QUERY="
set "REST=%*"
if "%~1"=="--" (
	set "REST=!REST:*-- =!"
	if "!REST!"=="--" set "REST="
) else if not "%~1"=="" (
	set "QUERY=%~1"
	set "REST=!REST:*%~1=!"
)
set "SRC="
if defined QUERY (
	for /f "delims=" %%p in ('""{{PICKER}}" worktree pick --repo "{{REPO}}" -- "!QUERY!""') do set "SRC=%%p"
	if not defined SRC exit /b 1
) else (
	rem No query: the interactive menu prints a path only for "run"; pin/unpin/
	rem cancel print nothing, so an empty result means there's nothing to run.
	for /f "delims=" %%p in ('""{{PICKER}}" worktree menu --repo "{{REPO}}""') do set "SRC=%%p"
	if not defined SRC exit /b 0
)
set "BRANCH=?"
for /f "delims=" %%b in ('git -C "!SRC!" rev-parse --abbrev-ref HEAD 2^>nul') do set "BRANCH=%%b"
echo {{NAME}}-wt -^> {{NAME}} !REST! @ !BRANCH!  (!SRC!)>&2
set "RIGSMITH_DEV_SRC=!SRC!"
call "{{DEV}}" !REST!
`
)

// writeWrapper writes the `-dev` and `-wt` launchers for one tool and returns
// their paths.
func writeWrapper(bin, name, repo, mod string) (devPath, wtPath string, err error) {
	var devTmpl, wtTmpl string
	if runtime.GOOS == "windows" {
		devPath = filepath.Join(bin, name+"-dev.cmd")
		wtPath = filepath.Join(bin, name+"-wt.cmd")
		devTmpl, wtTmpl = devWrapperCmd, wtWrapperCmd
	} else {
		devPath = filepath.Join(bin, name+"-dev")
		wtPath = filepath.Join(bin, name+"-wt")
		devTmpl, wtTmpl = devWrapperSh, wtWrapperSh
	}
	pickerName := "clauderig-dev"
	if runtime.GOOS == "windows" {
		pickerName = "clauderig-dev.cmd"
	}
	// route is the per-repo pin file the -dev wrapper reads; clauderig worktree
	// use/unset writes it. Baking the path in keeps -dev a plain cat (no slug
	// computation in the shell, no clauderig subprocess on the build fast path).
	route, err := devroute.RouteFile(repo)
	if err != nil {
		return "", "", err
	}
	repl := map[string]string{
		"{{NAME}}":   name,
		"{{REPO}}":   repo,
		"{{MOD}}":    mod,
		"{{ROUTE}}":  route,
		"{{DEV}}":    devPath,                        // -wt execs the sibling -dev launcher
		"{{PICKER}}": filepath.Join(bin, pickerName), // -wt's no-arg picker (clauderig owns worktrees)
	}
	if err = writeLauncher(devPath, devTmpl, repl); err != nil {
		return "", "", err
	}
	if err = writeLauncher(wtPath, wtTmpl, repl); err != nil {
		return "", "", err
	}
	return devPath, wtPath, nil
}

// writeLauncher renders a template (placeholder substitution, plus CRLF on
// Windows) and writes it as an executable file.
func writeLauncher(path, tmpl string, repl map[string]string) error {
	body := tmpl
	for k, v := range repl {
		body = strings.ReplaceAll(body, k, v)
	}
	if runtime.GOOS == "windows" {
		body = strings.ReplaceAll(body, "\n", "\r\n")
	}
	if err := os.WriteFile(path, []byte(body), 0o755); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}
	return nil
}

func printPathHint(bin string) {
	for _, p := range filepath.SplitList(os.Getenv("PATH")) {
		if p == bin {
			return // already on PATH
		}
	}
	fmt.Printf("\nNote: %s is not on your PATH. Add it:\n", bin)
	if runtime.GOOS == "windows" {
		fmt.Printf("  setx PATH \"%%PATH%%;%s\"\n", bin)
	} else {
		fmt.Printf("  export PATH=\"%s:$PATH\"   # add to ~/.zshrc or ~/.bashrc\n", bin)
	}
}
