package cli

import (
	"bytes"
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// rmStackspace builds a committed stackspace with two members on disk and a
// stale, rig-generated .NET overlay at the root — the state a hand removal
// leaves behind, and the one rm exists to clean up in one go. Each member
// arrives in a commit shaped like an import, so the unsent-work comparison
// has a baseline, as it does in a stackspace rig built.
func rmStackspace(t *testing.T, manifest string) string {
	return rmStackspaceWith(t, manifest, true)
}

// rmStackspaceWith is rmStackspace with the import markers optional: without
// them a member's tree cannot be compared against anything, which is its own
// case worth testing.
func rmStackspaceWith(t *testing.T, manifest string, markers bool) string {
	t.Helper()
	root := t.TempDir()
	mustGitStack(t, root, "init", "-q", "-b", "main")
	mustGitStack(t, root, "config", "user.email", "t@t")
	mustGitStack(t, root, "config", "user.name", "t")
	writeStackManifest(t, root, manifest)
	overlay := "<!-- generated by rig: package references redirected to sources in this tree -->\n<Project/>\n"
	if err := os.WriteFile(filepath.Join(root, "Directory.Build.targets"), []byte(overlay), 0o644); err != nil {
		t.Fatal(err)
	}
	mustGitStack(t, root, "add", "-A")
	mustGitStack(t, root, "commit", "-qm", "stack: stackspace manifest")
	for _, name := range []string{"pty-core", "term-core"} {
		p := filepath.Join(root, name, "src", "lib.cs")
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte("// code\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		mustGitStack(t, root, "add", "-A")
		msg := "add " + name
		if markers {
			msg = "stack: import " + name + " @ 0123456"
		}
		mustGitStack(t, root, "commit", "-qm", msg)
	}
	chdir(t, root)
	return root
}

func runRm(t *testing.T, args ...string) (string, error) {
	t.Helper()
	var buf bytes.Buffer
	cmd := newStackRemoveCmd()
	cmd.SetContext(context.Background())
	cmd.SetOut(&buf)
	cmd.SetErr(&buf)
	cmd.SetArgs(args)
	err := cmd.Execute()
	return buf.String(), err
}

const rmManifest = `{
  // comments must survive
  "repos": {
    // the library
    "pty-core":  { "upstream": "github.com/acme/pty-core", "fork": "github.com/you/pty-core" },
    "term-core": { "upstream": "github.com/acme/term-core", "fork": "github.com/you/term-core" }
  }
}
`

func TestStackRm(t *testing.T) {
	t.Run("removes the entry, the tree, the stale overlay, and commits", func(t *testing.T) {
		root := rmStackspace(t, rmManifest)
		out, err := runRm(t, "pty-core")
		if err != nil {
			t.Fatalf("%v\n%s", err, out)
		}
		m, _, err := loadStackManifest(root)
		if err != nil {
			t.Fatal(err)
		}
		if m.Repos["pty-core"] != nil || m.Repos["term-core"] == nil {
			t.Fatalf("repos after rm: %v", m.names())
		}
		body, _ := os.ReadFile(filepath.Join(root, "rig.stack.jsonc"))
		if !strings.Contains(string(body), "comments must survive") || strings.Contains(string(body), "the library") {
			t.Errorf("manifest comments mishandled:\n%s", body)
		}
		if _, err := os.Stat(filepath.Join(root, "pty-core")); !os.IsNotExist(err) {
			t.Error("pty-core/ still on disk")
		}
		if _, err := os.Stat(filepath.Join(root, "term-core", "src", "lib.cs")); err != nil {
			t.Error("term-core/ was touched")
		}
		if _, err := os.Stat(filepath.Join(root, "Directory.Build.targets")); !os.IsNotExist(err) {
			t.Error("stale generated overlay left in place")
		}
		if st := mustGitStack(t, root, "status", "--porcelain"); strings.TrimSpace(st) != "" {
			t.Errorf("removal not committed:\n%s", st)
		}
		if log := mustGitStack(t, root, "log", "-1", "--format=%s"); !strings.Contains(log, "stack: remove pty-core") {
			t.Errorf("commit subject = %q", log)
		}
		for _, want := range []string{"removed from", "deleted from the tree", "Directory.Build.targets removed", "committed"} {
			if !strings.Contains(out, want) {
				t.Errorf("output missing %q:\n%s", want, out)
			}
		}
	})

	t.Run("--keep-tree leaves the directory as an ordinary part of the repo", func(t *testing.T) {
		root := rmStackspace(t, rmManifest)
		if out, err := runRm(t, "pty-core", "--keep-tree"); err != nil {
			t.Fatalf("%v\n%s", err, out)
		}
		if _, err := os.Stat(filepath.Join(root, "pty-core", "src", "lib.cs")); err != nil {
			t.Error("--keep-tree deleted the directory")
		}
		m, _, _ := loadStackManifest(root)
		if m.Repos["pty-core"] != nil {
			t.Error("entry still in the manifest")
		}
	})

	t.Run("--keep-tree refuses a dirty prefix even with --force", func(t *testing.T) {
		root := rmStackspace(t, rmManifest)
		if err := os.WriteFile(filepath.Join(root, "pty-core", "src", "lib.cs"), []byte("// edited\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		for _, args := range [][]string{{"pty-core", "--keep-tree"}, {"pty-core", "--keep-tree", "--force"}} {
			if _, err := runRm(t, args...); err == nil || !strings.Contains(err.Error(), "commit or stash") {
				t.Fatalf("%v: err = %v, want a refusal", args, err)
			}
		}
		m, _, _ := loadStackManifest(root)
		if m.Repos["pty-core"] == nil {
			t.Error("entry removed from the manifest despite the refusal")
		}
		if got, _ := os.ReadFile(filepath.Join(root, "pty-core", "src", "lib.cs")); !strings.Contains(string(got), "edited") {
			t.Error("the edit was lost")
		}
	})

	t.Run("a tree with no import commit to compare against needs --force", func(t *testing.T) {
		withCursor := strings.TrimSuffix(rmManifest, "}\n") +
			`, "lastSync": { "pty-core": "0123456789abcdef0123456789abcdef01234567", "term-core": "89abcdef0123456789abcdef0123456789abcdef" }` + "\n}\n"
		root := rmStackspaceWith(t, withCursor, false)
		if _, err := runRm(t, "pty-core"); err == nil || !strings.Contains(err.Error(), "cannot tell") {
			t.Fatalf("err = %v, want a refusal that names the uncertainty", err)
		}
		if _, err := os.Stat(filepath.Join(root, "pty-core")); err != nil {
			t.Fatal("a refused rm still deleted the tree")
		}
		if out, err := runRm(t, "pty-core", "--force"); err != nil {
			t.Fatalf("%v\n%s", err, out)
		}
		m, _, err := loadStackManifest(root)
		if err != nil {
			t.Fatal(err)
		}
		if _, has := m.LastSync["pty-core"]; has || m.LastSync["term-core"] == "" {
			t.Errorf("lastSync after rm: %v", m.LastSync)
		}
	})

	t.Run("uncommitted edits under the prefix are refused", func(t *testing.T) {
		root := rmStackspace(t, rmManifest)
		if err := os.WriteFile(filepath.Join(root, "pty-core", "src", "lib.cs"), []byte("// edited\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := runRm(t, "pty-core"); err == nil || !strings.Contains(err.Error(), "uncommitted edits") {
			t.Fatalf("err = %v, want a refusal for uncommitted work", err)
		}
	})

	t.Run("--force takes untracked and ignored files with the tree", func(t *testing.T) {
		root := rmStackspace(t, rmManifest)
		for _, f := range []string{"pty-core/bin/out.dll", "pty-core/notes.txt"} {
			p := filepath.Join(root, filepath.FromSlash(f))
			if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(p, []byte("x"), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		if err := os.WriteFile(filepath.Join(root, ".gitignore"), []byte("bin/\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		mustGitStack(t, root, "add", ".gitignore")
		mustGitStack(t, root, "commit", "-qm", "ignore bin")
		if out, err := runRm(t, "pty-core", "--force"); err != nil {
			t.Fatalf("%v\n%s", err, out)
		}
		if _, err := os.Stat(filepath.Join(root, "pty-core")); !os.IsNotExist(err) {
			t.Error("pty-core/ left behind with its untracked and ignored files")
		}
		if files := mustGitStack(t, root, "ls-tree", "-r", "--name-only", "HEAD"); strings.Contains(files, "notes.txt") {
			t.Error("an untracked file was committed by the removal")
		}
	})

	t.Run("--force discards uncommitted edits under the prefix", func(t *testing.T) {
		root := rmStackspace(t, rmManifest)
		if err := os.WriteFile(filepath.Join(root, "pty-core", "src", "lib.cs"), []byte("// edited\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if out, err := runRm(t, "pty-core", "--force"); err != nil {
			t.Fatalf("%v\n%s", err, out)
		}
		if _, err := os.Stat(filepath.Join(root, "pty-core")); !os.IsNotExist(err) {
			t.Error("pty-core/ still on disk after --force")
		}
		if st := mustGitStack(t, root, "status", "--porcelain"); strings.TrimSpace(st) != "" {
			t.Errorf("removal not committed:\n%s", st)
		}
	})

	t.Run("an inline stack block in .rig.json loses the entry too", func(t *testing.T) {
		root := t.TempDir()
		mustGitStack(t, root, "init", "-q", "-b", "main")
		mustGitStack(t, root, "config", "user.email", "t@t")
		mustGitStack(t, root, "config", "user.name", "t")
		if err := os.WriteFile(filepath.Join(root, ".rig.json"), []byte(`{
  "stack": {
    "repos": {
      "pty-core":  { "upstream": "github.com/acme/pty-core", "fork": "github.com/you/pty-core" },
      "term-core": { "upstream": "github.com/acme/term-core", "fork": "github.com/you/term-core" }
    },
    "lastSync": { "pty-core": "0123456789abcdef0123456789abcdef01234567", "term-core": "89abcdef0123456789abcdef0123456789abcdef" }
  }
}
`), 0o644); err != nil {
			t.Fatal(err)
		}
		for _, f := range []string{"pty-core/src/lib.cs", "term-core/src/lib.cs"} {
			p := filepath.Join(root, filepath.FromSlash(f))
			if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
				t.Fatal(err)
			}
			if err := os.WriteFile(p, []byte("// code\n"), 0o644); err != nil {
				t.Fatal(err)
			}
		}
		mustGitStack(t, root, "add", "-A")
		mustGitStack(t, root, "commit", "-qm", "stackspace")
		chdir(t, root)
		if out, err := runRm(t, "pty-core", "--force"); err != nil {
			t.Fatalf("%v\n%s", err, out)
		}
		m, _, err := loadStackManifest(root)
		if err != nil {
			t.Fatal(err)
		}
		if m.Repos["pty-core"] != nil || m.Repos["term-core"] == nil || m.LastSync["pty-core"] != "" || m.LastSync["term-core"] == "" {
			t.Fatalf("after rm: repos=%v lastSync=%v", m.names(), m.LastSync)
		}
	})

	t.Run("uncommitted changes elsewhere are refused too", func(t *testing.T) {
		root := rmStackspace(t, rmManifest)
		if err := os.WriteFile(filepath.Join(root, "term-core", "src", "lib.cs"), []byte("// edited\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := runRm(t, "pty-core"); err == nil || !strings.Contains(err.Error(), "outside pty-core/") {
			t.Fatalf("err = %v, want a refusal naming the dirty tree", err)
		}
	})

	t.Run("a manifest-only entry with no directory needs no --force", func(t *testing.T) {
		root := rmStackspace(t, strings.Replace(rmManifest, `"term-core": {`, `"ghost": { "upstream": "github.com/acme/ghost", "fork": "github.com/you/ghost" },
    "term-core": {`, 1))
		if out, err := runRm(t, "ghost"); err != nil {
			t.Fatalf("%v\n%s", err, out)
		}
		m, _, err := loadStackManifest(root)
		if err != nil {
			t.Fatal(err)
		}
		if m.Repos["ghost"] != nil || len(m.Repos) != 2 {
			t.Fatalf("repos after rm: %v", m.names())
		}
	})

	t.Run("an overlay that cannot be rewritten puts everything back", func(t *testing.T) {
		// Three members with a cross-member package reference between the two
		// that stay, and an overlay somebody wrote by hand at the root: wire
		// refuses to clobber it, and rm must then leave the stackspace as it
		// found it rather than half-removed and uncommitted.
		root := t.TempDir()
		mustGitStack(t, root, "init", "-q", "-b", "main")
		mustGitStack(t, root, "config", "user.email", "t@t")
		mustGitStack(t, root, "config", "user.name", "t")
		writeStackManifest(t, root, `{"repos": {
  "app":  {"upstream": "github.com/you/app",  "fork": "github.com/you/app", "owned": true},
  "lib":  {"upstream": "github.com/acme/lib", "fork": "github.com/you/lib"},
  "gone": {"upstream": "github.com/acme/gone", "fork": "github.com/you/gone"}
}}`)
		csproj(t, root, "lib/src/Acme.Lib", "Acme.Lib")
		csproj(t, root, "app/src/App", "Term.App", "Acme.Lib")
		csproj(t, root, "gone/src/Gone", "Acme.Gone")
		if err := os.WriteFile(filepath.Join(root, "Directory.Build.targets"), []byte("<Project><!-- mine --></Project>\n"), 0o644); err != nil {
			t.Fatal(err)
		}
		mustGitStack(t, root, "add", "-A")
		mustGitStack(t, root, "commit", "-qm", "stack: stackspace manifest")
		for _, n := range []string{"app", "lib", "gone"} {
			mustGitStack(t, root, "commit", "-q", "--allow-empty", "-m", "stack: import "+n+" @ 0123456")
		}
		chdir(t, root)
		head := strings.TrimSpace(mustGitStack(t, root, "rev-parse", "HEAD"))

		out, err := runRm(t, "gone")
		if err == nil || !strings.Contains(err.Error(), "rig did not write") || !strings.Contains(err.Error(), "put back") {
			t.Fatalf("err = %v\n%s", err, out)
		}
		m, _, lerr := loadStackManifest(root)
		if lerr != nil || m.Repos["gone"] == nil {
			t.Fatalf("manifest not put back: %v, %v", m.names(), lerr)
		}
		if _, serr := os.Stat(filepath.Join(root, "gone", "src", "Gone", "Gone.csproj")); serr != nil {
			t.Error("gone/ not put back")
		}
		if got := strings.TrimSpace(mustGitStack(t, root, "rev-parse", "HEAD")); got != head {
			t.Error("a failed rm still committed")
		}
		if st := strings.TrimSpace(mustGitStack(t, root, "status", "--porcelain")); st != "" {
			t.Errorf("failed rm left the tree dirty:\n%s", st)
		}
	})

	t.Run("an unknown repo names the ones that exist", func(t *testing.T) {
		rmStackspace(t, rmManifest)
		if _, err := runRm(t, "nope"); err == nil || !strings.Contains(err.Error(), "pty-core, term-core") {
			t.Fatalf("err = %v", err)
		}
	})
}
