package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// The README a stackspace seed does not have.
//
// A seed repo is a manifest, a build overlay, and nothing that says what either
// is. The member directories are absent on purpose — they are reconstituted by
// `rig stack init` rather than committed — but the natural reading of a repo
// whose build file points at `porta-pty/src/…` with no `porta-pty/` is that the
// repo is broken. Someone then either gives up or, worse, helpfully commits the
// members and undoes the arrangement.
//
// Almost all of it is derivable from the manifest, which is the argument for
// generating it: a hand-written one goes stale the first time a member is added,
// and the two things that actually bite are the two nobody thinks to write down.
const stackReadmeMarker = "<!-- generated by rig: this file is rewritten by `rig stack init` and `rig stack wire`; delete this line to make it yours -->"

// stackReadmePath is where the generated README lives.
func stackReadmePath(root string) string { return filepath.Join(root, "README.md") }

// writeStackReadme writes the generated README unless one is already there that
// rig does not own.
//
// The same rule the build overlay uses: a file carrying the marker is rig's to
// rewrite, and a file without it belongs to whoever wrote it. Dropping the
// marker line is how you take ownership — stated in the marker itself, so the
// answer is in the file rather than in documentation about the file.
//
// Reports whether it wrote, so callers can say so rather than being silent
// about creating a file in someone's repo.
func writeStackReadme(root string, m *stackManifest) (bool, error) {
	path := stackReadmePath(root)
	switch body, err := os.ReadFile(path); {
	case err == nil && !strings.Contains(string(body), stackReadmeMarker):
		return false, nil // theirs
	case err != nil && !os.IsNotExist(err):
		return false, err
	}
	next := renderStackReadme(root, m)
	if err := os.WriteFile(path, []byte(next), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// renderStackReadme builds the README from the manifest.
func renderStackReadme(root string, m *stackManifest) string {
	name := filepath.Base(root)
	var b strings.Builder

	fmt.Fprintf(&b, "# %s\n\n", name)
	b.WriteString(stackReadmeMarker + "\n\n")

	b.WriteString("A **stackspace**: several upstream repositories fused into one git history, " +
		"each under its own directory. A change can span them in one commit and the build " +
		"compiles against source rather than published packages — and each project still " +
		"leaves as an ordinary pull request to its own upstream.\n\n")

	// The members, straight out of the manifest. The table is the part a hand
	// written README gets wrong first, because it goes stale the moment a member
	// is added.
	if m != nil && len(m.Repos) > 0 {
		b.WriteString("## What is in here\n\n")
		b.WriteString("| Directory | Upstream | Fork |\n|---|---|---|\n")
		names := make([]string, 0, len(m.Repos))
		for n := range m.Repos {
			names = append(names, n)
		}
		sort.Strings(names)
		for _, n := range names {
			r := m.Repos[n]
			fmt.Fprintf(&b, "| `%s/` | %s | %s |\n", n, mdRepo(r.Upstream), mdRepo(r.Fork))
		}
		b.WriteString("\n")
	}

	b.WriteString("## The directories are not in this repository\n\n")
	b.WriteString("That is deliberate, and it is the thing worth reading twice. What is committed " +
		"here is the manifest and the build wiring; the member directories are rebuilt from " +
		"their upstreams by `rig stack init`. A fresh clone therefore looks broken — a build " +
		"file pointing at directories that are not there — until it is set up.\n\n")
	b.WriteString("**Do not commit the members.** Storing them here would replace a reconstructible " +
		"arrangement with a copy that drifts from the upstreams it came from.\n\n")

	b.WriteString("## Setting it up\n\n")
	b.WriteString("```sh\n")
	b.WriteString("curl -fsSL https://rigsmith.sh/rig | sh   # if rig is not installed\n")
	b.WriteString("rig stack setup\n")
	b.WriteString("```\n\n")
	b.WriteString("`setup` installs the fusion engine, reconstitutes the members, writes the build " +
		"overlay if it is missing, and prints the status. It is the one command a fresh clone " +
		"needs.\n\n")

	b.WriteString("## Working in it\n\n")
	b.WriteString("```sh\n")
	b.WriteString("rig build                       # compiles across members, from source\n")
	b.WriteString("rig stack status                # each member against its upstream\n")
	b.WriteString("rig stack pull                  # take new upstream commits\n")
	b.WriteString("rig stack propose <dir> <name>  # send one project's work to its fork as a PR branch\n")
	b.WriteString("```\n\n")

	b.WriteString("## Two rules that bite first\n\n")
	b.WriteString("**Never `git push` from this workspace.** It holds several rewritten histories " +
		"fused together; pushing it anywhere would publish that fusion. Work leaves through " +
		"`rig stack propose`, which reconstructs one project's changes as a branch on its fork, " +
		"at the real paths, rooted on upstream.\n\n")
	// A clone arrives with the very remote the rule above warns about, so
	// "never add one" is advice that arrives after the fact.
	b.WriteString("If this was cloned from a seed repository it already has an `origin`, and that " +
		"is the remote the rule is about — a stray `git push` would put the fused history " +
		"where the seed lives. Once it is set up there is nothing more to take from it:\n\n")
	b.WriteString("```sh\n")
	b.WriteString("git remote -v            # if there is an origin, it is the seed\n")
	b.WriteString("git remote remove origin\n")
	b.WriteString("```\n\n")
	b.WriteString("Keep it only if you intend to pull manifest updates from the seed, and never " +
		"push to it.\n\n")
	b.WriteString("**Keep the tree clean before `init`, `pull` and `propose`.** They refuse a dirty " +
		"tree on purpose: an import stages everything, and would swallow uncommitted edits.\n\n")

	b.WriteString("## Reading `rig stack status`\n\n")
	b.WriteString("One line per member:\n\n")
	b.WriteString("- **in step** — the member is at the same upstream commit it was imported from.\n")
	b.WriteString("- **behind by N** — upstream has moved; `rig stack pull` takes those commits.\n")
	b.WriteString("- **N to send** — this workspace holds changes to that project that its fork does " +
		"not; `rig stack propose` is how they leave.\n")
	b.WriteString("- **cannot tell** — there is no import commit in this history yet, so the " +
		"comparison has nothing to stand on. Usually means `rig stack init` has not run.\n\n")

	b.WriteString("## This file is generated\n\n")
	b.WriteString("`rig stack init` and `rig stack wire` rewrite it, so edits made while the " +
		"marker near the top is still there are lost on the next run. **Delete the marker " +
		"line** and the file becomes yours; rig then leaves it alone for good.\n\n")

	fmt.Fprintf(&b, "Full guide: <https://rigsmith.dev/rig/stack>.\n")
	return b.String()
}

// mdRepo renders a repo reference as a link when it looks like a URL, and as
// plain text otherwise — a manifest may carry an ssh remote or a local path,
// and linking those produces something that does not resolve.
func mdRepo(s string) string {
	if s == "" {
		return "—"
	}
	// The manifest normalises a remote to host/owner/repo, so what arrives here
	// is usually scheme-less and would never have matched a prefix check.
	trimmed := strings.TrimPrefix(strings.TrimPrefix(s, "https://"), "http://")
	if parts := strings.Split(trimmed, "/"); len(parts) == 3 &&
		strings.Contains(parts[0], ".") && // a host, rather than the first
		!strings.HasPrefix(parts[0], ".") && // segment of a relative path
		!strings.ContainsAny(trimmed, " @:") {
		return "[" + trimmed + "](https://" + trimmed + ")"
	}
	// An ssh remote or a local path: linking it produces something that does
	// not resolve, so show it as it is.
	return "`" + s + "`"
}
