package commands

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
	"unicode"

	"github.com/rigsmith/rigsmith/internal/agentrig/durable"
	"github.com/rigsmith/rigsmith/internal/agentrig/queue"
)

// These files are fixed format-v1 inputs, not regenerated by the production
// writer. Changing reader and writer together cannot silently change their bytes.
func TestQueueHookRoutingPersistedFormatV1(t *testing.T) {
	platform, base := "unix", "/home/fixture/.clauderig"
	if runtime.GOOS == "windows" {
		platform, base = "windows", `C:\Users\fixture\.clauderig`
	}
	for _, mode := range []string{"enabled", "disabled"} {
		t.Run(mode, func(t *testing.T) {
			golden, err := os.ReadFile(filepath.Join("testdata", "hook-routing", platform+"-"+mode+".json"))
			if err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(t.TempDir(), "queue-hooks.json")
			if err := os.WriteFile(path, golden, 0600); err != nil {
				t.Fatal(err)
			}
			saved, err := loadHookRouting(path)
			if err != nil {
				t.Fatal(err)
			}
			if saved.Version != 1 || saved.Enabled != (mode == "enabled") || saved.Runtime != filepath.Join(base, "queue-runtime") || saved.Inbox != filepath.Join(base, "hook-inbox") || !reflect.DeepEqual(saved.Profiles, []string{"work"}) || saved.Scope != strings.Repeat("1", 64) || !saved.UnknownIdentity {
				t.Fatalf("lost persisted fields: %+v", saved)
			}
			if err := saveHookRouting(t.Context(), path, saved); err != nil {
				t.Fatal(err)
			}
			actual, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(actual, golden) {
				t.Fatal("format-v1 reflush changed bytes", string(actual), err)
			}
			restarted, err := loadHookRouting(path)
			if err != nil || !reflect.DeepEqual(saved, restarted) {
				t.Fatal("restart changed persisted fields", restarted, err)
			}
		})
	}
}

func TestQueueHookRoutingUncertainWrites(t *testing.T) {
	for _, operation := range []string{"enable", "disable", "route"} {
		for _, after := range []bool{false, true} {
			name := operation + "/before-replacement"
			if after {
				name = operation + "/after-replacement"
			}
			t.Run(name, func(t *testing.T) {
				f := newQueueFixture(t)
				path, _ := setupHookRouting(t, f)
				f.must(t, "init")
				if operation != "enable" {
					f.must(t, "enable-hooks")
				}
				inbox := filepath.Join(filepath.Dir(path), "hook-inbox")
				if operation == "route" {
					// Preserve both a confirmed queued event and its uncertain producer record.
					r := f.open(t)
					saved, err := newQueueSubmission(r, "s", queue.Flush{Mode: queue.Normal}, false, f.deps.identity)
					if err != nil {
						t.Fatal(err)
					}
					if _, err := r.Enqueue(t.Context(), saved.Identity, saved.Request, saved.At); err != nil {
						t.Fatal(err)
					}
					state := hookInboxState{Version: 1, Scope: r.ScopeID(), Requests: []queueSubmission{saved}}
					if err := (hookInbox{dir: inbox, save: durable.Write}).persist(t.Context(), state); err != nil {
						t.Fatal(err)
					}
				}
				snapshot := func() []byte {
					t.Helper()
					work, err := f.open(t).Snapshot(t.Context())
					if err != nil {
						t.Fatal(err)
					}
					data, err := json.Marshal(work)
					if err != nil {
						t.Fatal(err)
					}
					return data
				}
				queueBefore := snapshot()
				inboxBefore, _ := os.ReadFile(filepath.Join(inbox, "requests.json"))
				reads := f.reads
				injected := errors.New("uncertain descriptor write")
				f.deps.saveRouting = func(ctx context.Context, path string, s queueHookRouting) error {
					if after {
						if err := saveHookRouting(ctx, path, s); err != nil {
							return err
						}
					}
					return injected
				}
				source := filepath.Join(f.req.Machine.Home, ".claude", "projects", "-fixture", "s.jsonl")
				run := func() error {
					if operation == "route" {
						_, _, err := routedSync(f, t.Context(), queueHookJSON(t, "Stop", "s", source), "--hook")
						return err
					}
					_, err := f.execute(t.Context(), operation+"-hooks")
					return err
				}
				if err := run(); !errors.Is(err, injected) {
					t.Fatal("write uncertainty hidden", err)
				}
				if f.reads != reads {
					t.Fatal("failed descriptor write reached producer identity")
				}
				if !bytes.Equal(queueBefore, snapshot()) {
					t.Fatal("failed descriptor write changed queue")
				}
				inboxAfter, err := os.ReadFile(filepath.Join(inbox, "requests.json"))
				if err != nil {
					t.Fatal(err)
				}
				if operation != "enable" && !bytes.Equal(inboxBefore, inboxAfter) {
					t.Fatal("failed descriptor write changed inbox")
				}
				// A pre-replacement first enable has no descriptor; every other state must
				// still be readable, retaining either the old or the requested routing mode.
				saved, err := loadHookRouting(path)
				if operation == "enable" && !after {
					if !os.IsNotExist(err) {
						t.Fatal(saved, err)
					}
				} else if err != nil || saved.Enabled != (operation != "disable" || !after) {
					t.Fatal(saved, err)
				}
				f.deps.saveRouting = nil
				if err := run(); err != nil {
					t.Fatal("same-command retry failed", err)
				}
				saved, err = loadHookRouting(path)
				if err != nil || saved.Enabled != (operation != "disable") {
					t.Fatal(saved, err)
				}
				state, err := (hookInbox{dir: inbox}).load(saved.Scope)
				if err != nil || len(state.Requests) != 0 {
					t.Fatal(state, err)
				}
				if operation == "route" {
					work, err := f.open(t).Snapshot(t.Context())
					if err != nil {
						t.Fatal(err)
					}
					count := 0
					for _, batch := range work {
						count += len(batch.Events)
					}
					if count != 2 {
						t.Fatal("retry lost or duplicated saved events", work)
					}
				}
			})
		}
	}
}

func TestQueueHookRoutingPartialDescriptorRestart(t *testing.T) {
	for _, cut := range []string{"empty", "partial", "missing-lf"} {
		t.Run(cut, func(t *testing.T) {
			f := newQueueFixture(t)
			path, _ := setupHookRouting(t, f)
			f.must(t, "init")
			f.must(t, "enable-hooks")
			saved, err := loadHookRouting(path)
			if err != nil {
				t.Fatal(err)
			}
			before, _ := os.ReadFile(filepath.Join(saved.Inbox, "requests.json"))
			data, _ := os.ReadFile(path)
			switch cut {
			case "empty":
				data = nil
			case "partial":
				data = data[:len(data)/2]
			case "missing-lf":
				data = data[:len(data)-1]
			}
			if err := os.WriteFile(path, data, 0600); err != nil {
				t.Fatal(err)
			}
			for _, command := range []string{"enable-hooks", "disable-hooks", "hook-status"} {
				if _, err := f.execute(t.Context(), command); err == nil {
					t.Fatal("accepted partial descriptor", command)
				}
			}
			source := filepath.Join(f.req.Machine.Home, ".claude", "projects", "-fixture", "s.jsonl")
			if _, _, err := routedSync(f, t.Context(), queueHookJSON(t, "Stop", "s", source), "--hook"); err == nil {
				t.Fatal("partial descriptor fell through to sync")
			}
			after, _ := os.ReadFile(filepath.Join(saved.Inbox, "requests.json"))
			if !bytes.Equal(before, after) {
				t.Fatal("restart changed inbox")
			}
			actual, _ := os.ReadFile(path)
			if !bytes.Equal(data, actual) {
				t.Fatal("restart reset partial descriptor")
			}
			work, err := f.open(t).Snapshot(t.Context())
			if err != nil || len(work) != 0 || f.reads != 0 {
				t.Fatal(work, err, f.reads)
			}
		})
	}
}

func TestQueueHookRoutingFilesystemCaseAndAliases(t *testing.T) {
	f := newQueueFixture(t)
	_, _ = setupHookRouting(t, f)
	f.must(t, "init")
	r := f.open(t)
	// Keep this geometry separate from the runtime's independently conservative
	// capture/profile exclusions. A .CLAUDERIG inbox overlaps that protected
	// profile tree under those rules, even on a case-sensitive volume.
	original := filepath.Join(t.TempDir(), "routing")
	if err := os.Mkdir(original, 0700); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(original, "queue-hooks.json")
	if err := checkRoutingPaths(r, path, original); err == nil {
		t.Fatal("allowed containing inbox")
	}
	distinct := filepath.Join(filepath.Dir(original), "ROUTING")
	if err := os.Mkdir(distinct, 0700); err != nil && !os.IsExist(err) {
		t.Fatal(err)
	}
	a, err := os.Stat(original)
	if err != nil {
		t.Fatal(err)
	}
	b, err := os.Stat(distinct)
	if err != nil {
		t.Fatal(err)
	}
	if err := checkRoutingPaths(r, path, distinct); (err != nil) != os.SameFile(a, b) {
		t.Fatal("did not follow filesystem case semantics", err)
	}
	alias := filepath.Join(filepath.Dir(f.dir), "alias")
	if err := os.Symlink(original, alias); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := checkRoutingPaths(r, path, alias); err == nil {
		t.Fatal("allowed containing inbox through alias")
	}
}

func TestQueueHookRoutingIncompleteInboxDiagnostic(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Win32 forbids control characters in directory names")
	}
	f := newQueueFixture(t)
	_, _ = setupHookRouting(t, f)
	f.must(t, "init")
	inbox := filepath.Join(t.TempDir(), "incomplete-\x1b[31m-\t-inbox")
	if err := os.Mkdir(inbox, 0700); err != nil {
		t.Fatal(err)
	}
	_, err := f.execute(t.Context(), "enable-hooks", "--inbox", inbox)
	if err == nil || !strings.Contains(err.Error(), "incomplete hook inbox") || strings.IndexFunc(err.Error(), unicode.IsControl) >= 0 {
		t.Fatal("unsafe or missing diagnostic", err)
	}
}
