package commands

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"testing"
	"unicode"

	"github.com/rigsmith/rigsmith/internal/agentrig/durable"
	"github.com/rigsmith/rigsmith/internal/agentrig/queue"
	"github.com/rigsmith/rigsmith/internal/agentrig/storelock"
	"github.com/rigsmith/rigsmith/internal/clauderig/service"
)

// These files are fixed format-v1 inputs, not regenerated by the production
// writer. Changing reader and writer together cannot silently change their bytes.
func TestQueueHookRoutingPersistedFormatV1(t *testing.T) {
	platform, base := "unix", "/home/fixture/.clauderig"
	if runtime.GOOS == "windows" {
		platform, base = "windows", `C:\Users\fixture\.clauderig`
	}
	for _, mode := range []string{"enabled", "disabled"} {
		t.Run(mode, func(t *testing.T) {
			golden, err := os.ReadFile(filepath.Join("testdata", "hook-routing", platform+"-"+mode+".json"))
			if err != nil {
				t.Fatal(err)
			}
			path := filepath.Join(t.TempDir(), "queue-hooks.json")
			if err := os.WriteFile(path, golden, 0600); err != nil {
				t.Fatal(err)
			}
			saved, err := loadHookRouting(path)
			if err != nil {
				t.Fatal(err)
			}
			if saved.Version != 1 || saved.Enabled != (mode == "enabled") || saved.Runtime != filepath.Join(base, "queue-runtime") || saved.Inbox != filepath.Join(base, "hook-inbox") || !reflect.DeepEqual(saved.Profiles, []string{"work"}) || saved.Scope != strings.Repeat("1", 64) || !saved.UnknownIdentity {
				t.Fatalf("lost persisted fields: %+v", saved)
			}
			if err := saveHookRouting(t.Context(), path, saved); err != nil {
				t.Fatal(err)
			}
			actual, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(actual, golden) {
				t.Fatal("format-v1 reflush changed bytes", string(actual), err)
			}
			restarted, err := loadHookRouting(path)
			if err != nil || !reflect.DeepEqual(saved, restarted) {
				t.Fatal("restart changed persisted fields", restarted, err)
			}
		})
	}
}

func TestQueueHookRoutingUncertainWrites(t *testing.T) {
	for _, operation := range []string{"enable", "disable", "route"} {
		for _, after := range []bool{false, true} {
			name := operation + "/before-replacement"
			if after {
				name = operation + "/after-replacement"
			}
			t.Run(name, func(t *testing.T) {
				f := newQueueFixture(t)
				path, _ := setupHookRouting(t, f)
				f.must(t, "init")
				if operation != "enable" {
					f.must(t, "enable-hooks")
				}
				inbox := filepath.Join(filepath.Dir(path), "hook-inbox")
				if operation == "route" {
					// Preserve both a confirmed queued event and its uncertain producer record.
					r := f.open(t)
					saved, err := newQueueSubmission(r, "s", queue.Flush{Mode: queue.Normal}, false, f.deps.identity)
					if err != nil {
						t.Fatal(err)
					}
					if _, err := r.Enqueue(t.Context(), saved.Identity, saved.Request, saved.At); err != nil {
						t.Fatal(err)
					}
					state := hookInboxState{Version: 1, Scope: r.ScopeID(), Requests: []queueSubmission{saved}}
					if err := (hookInbox{dir: inbox, save: durable.Write}).persist(t.Context(), state); err != nil {
						t.Fatal(err)
					}
				}
				snapshot := func() []byte {
					t.Helper()
					work, err := f.open(t).Snapshot(t.Context())
					if err != nil {
						t.Fatal(err)
					}
					data, err := json.Marshal(work)
					if err != nil {
						t.Fatal(err)
					}
					return data
				}
				queueBefore := snapshot()
				inboxBefore, _ := os.ReadFile(filepath.Join(inbox, "requests.json"))
				reads := f.reads
				injected := errors.New("uncertain descriptor write")
				f.deps.saveRouting = func(ctx context.Context, path string, s queueHookRouting) error {
					if after {
						if err := saveHookRouting(ctx, path, s); err != nil {
							return err
						}
					}
					return injected
				}
				source := filepath.Join(f.req.Machine.Home, ".claude", "projects", "-fixture", "s.jsonl")
				run := func() error {
					if operation == "route" {
						_, _, err := routedSync(f, t.Context(), queueHookJSON(t, "Stop", "s", source), "--hook")
						return err
					}
					_, err := f.execute(t.Context(), operation+"-hooks")
					return err
				}
				if err := run(); !errors.Is(err, injected) {
					t.Fatal("write uncertainty hidden", err)
				}
				if f.reads != reads {
					t.Fatal("failed descriptor write reached producer identity")
				}
				if !bytes.Equal(queueBefore, snapshot()) {
					t.Fatal("failed descriptor write changed queue")
				}
				inboxAfter, err := os.ReadFile(filepath.Join(inbox, "requests.json"))
				if err != nil {
					t.Fatal(err)
				}
				if operation != "enable" && !bytes.Equal(inboxBefore, inboxAfter) {
					t.Fatal("failed descriptor write changed inbox")
				}
				// A pre-replacement first enable has no descriptor; every other state must
				// still be readable, retaining either the old or the requested routing mode.
				saved, err := loadHookRouting(path)
				if operation == "enable" && !after {
					if !os.IsNotExist(err) {
						t.Fatal(saved, err)
					}
				} else if err != nil || saved.Enabled != (operation != "disable" || !after) {
					t.Fatal(saved, err)
				}
				f.deps.saveRouting = nil
				if err := run(); err != nil {
					t.Fatal("same-command retry failed", err)
				}
				saved, err = loadHookRouting(path)
				if err != nil || saved.Enabled != (operation != "disable") {
					t.Fatal(saved, err)
				}
				state, err := (hookInbox{dir: inbox}).load(saved.Scope)
				if err != nil || len(state.Requests) != 0 {
					t.Fatal(state, err)
				}
				if operation == "route" {
					work, err := f.open(t).Snapshot(t.Context())
					if err != nil {
						t.Fatal(err)
					}
					count := 0
					for _, batch := range work {
						count += len(batch.Events)
					}
					if count != 2 {
						t.Fatal("retry lost or duplicated saved events", work)
					}
				}
			})
		}
	}
}

func TestQueueHookRoutingPartialDescriptorRestart(t *testing.T) {
	for _, cut := range []string{"empty", "partial", "missing-lf"} {
		t.Run(cut, func(t *testing.T) {
			f := newQueueFixture(t)
			path, _ := setupHookRouting(t, f)
			f.must(t, "init")
			f.must(t, "enable-hooks")
			saved, err := loadHookRouting(path)
			if err != nil {
				t.Fatal(err)
			}
			before, _ := os.ReadFile(filepath.Join(saved.Inbox, "requests.json"))
			data, _ := os.ReadFile(path)
			switch cut {
			case "empty":
				data = nil
			case "partial":
				data = data[:len(data)/2]
			case "missing-lf":
				data = data[:len(data)-1]
			}
			if err := os.WriteFile(path, data, 0600); err != nil {
				t.Fatal(err)
			}
			for _, command := range []string{"enable-hooks", "disable-hooks", "hook-status"} {
				if _, err := f.execute(t.Context(), command); err == nil {
					t.Fatal("accepted partial descriptor", command)
				}
			}
			source := filepath.Join(f.req.Machine.Home, ".claude", "projects", "-fixture", "s.jsonl")
			if _, _, err := routedSync(f, t.Context(), queueHookJSON(t, "Stop", "s", source), "--hook"); err == nil {
				t.Fatal("partial descriptor fell through to sync")
			}
			after, _ := os.ReadFile(filepath.Join(saved.Inbox, "requests.json"))
			if !bytes.Equal(before, after) {
				t.Fatal("restart changed inbox")
			}
			actual, _ := os.ReadFile(path)
			if !bytes.Equal(data, actual) {
				t.Fatal("restart reset partial descriptor")
			}
			work, err := f.open(t).Snapshot(t.Context())
			if err != nil || len(work) != 0 || f.reads != 0 {
				t.Fatal(work, err, f.reads)
			}
		})
	}
}

func TestQueueHookRoutingFilesystemCaseAndAliases(t *testing.T) {
	f := newQueueFixture(t)
	_, _ = setupHookRouting(t, f)
	f.must(t, "init")
	r := f.open(t)
	// Keep this geometry separate from the runtime's independently conservative
	// capture/profile exclusions. A .CLAUDERIG inbox overlaps that protected
	// profile tree under those rules, even on a case-sensitive volume.
	original := filepath.Join(t.TempDir(), "routing")
	if err := os.Mkdir(original, 0700); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(original, "queue-hooks.json")
	if err := checkRoutingPaths(r, path, original); err == nil {
		t.Fatal("allowed containing inbox")
	}
	distinct := filepath.Join(filepath.Dir(original), "ROUTING")
	if err := os.Mkdir(distinct, 0700); err != nil && !os.IsExist(err) {
		t.Fatal(err)
	}
	a, err := os.Stat(original)
	if err != nil {
		t.Fatal(err)
	}
	b, err := os.Stat(distinct)
	if err != nil {
		t.Fatal(err)
	}
	if err := checkRoutingPaths(r, path, distinct); (err != nil) != os.SameFile(a, b) {
		t.Fatal("did not follow filesystem case semantics", err)
	}
	alias := filepath.Join(filepath.Dir(f.dir), "alias")
	if err := os.Symlink(original, alias); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	if err := checkRoutingPaths(r, path, alias); err == nil {
		t.Fatal("allowed containing inbox through alias")
	}
}

func TestQueueHookRoutingIncompleteInboxDiagnostic(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("Win32 forbids control characters in directory names")
	}
	f := newQueueFixture(t)
	_, _ = setupHookRouting(t, f)
	f.must(t, "init")
	inbox := filepath.Join(t.TempDir(), "incomplete-\x1b[31m-\t-inbox")
	if err := os.Mkdir(inbox, 0700); err != nil {
		t.Fatal(err)
	}
	_, err := f.execute(t.Context(), "enable-hooks", "--inbox", inbox)
	if err == nil || !strings.Contains(err.Error(), "incomplete hook inbox") || strings.IndexFunc(err.Error(), unicode.IsControl) >= 0 {
		t.Fatal("unsafe or missing diagnostic", err)
	}
}

func TestQueueHookRoutingDisabledRetryRechecksWork(t *testing.T) {
	for _, mode := range []string{"inbox", "queue", "worker", "missing-inbox"} {
		t.Run(mode, func(t *testing.T) {
			f := newQueueFixture(t)
			path, _ := setupHookRouting(t, f)
			f.must(t, "init")
			f.must(t, "enable-hooks")
			f.must(t, "disable-hooks")
			saved, err := loadHookRouting(path)
			if err != nil {
				t.Fatal(err)
			}
			original, err := os.ReadFile(path)
			if err != nil {
				t.Fatal(err)
			}
			switch mode {
			case "inbox":
				request, err := newQueueSubmission(f.open(t), "s", queue.Flush{Mode: queue.Normal}, false, f.deps.identity)
				if err != nil {
					t.Fatal(err)
				}
				if err := (hookInbox{dir: saved.Inbox, save: durable.Write}).persist(t.Context(), hookInboxState{Version: 1, Scope: saved.Scope, Requests: []queueSubmission{request}}); err != nil {
					t.Fatal(err)
				}
			case "queue":
				file := filepath.Join(t.TempDir(), "request")
				f.must(t, "prepare", "--session", "s", "--output", file)
				f.must(t, "enqueue", file)
			case "worker":
				_, release, err := storelock.Acquire(t.Context(), filepath.Join(f.dir, "queue", "worker"), 0)
				if err != nil {
					t.Fatal(err)
				}
				defer release()
			case "missing-inbox":
				if err := os.RemoveAll(saved.Inbox); err != nil {
					t.Fatal(err)
				}
			}
			if _, err := f.execute(t.Context(), "disable-hooks"); err == nil {
				t.Fatal("disabled retry skipped rollback safeguards", mode)
			}
			after, err := os.ReadFile(path)
			if err != nil || !bytes.Equal(original, after) {
				t.Fatal("failed retry changed descriptor", err)
			}
		})
	}
}

func TestQueueHookRoutingDisableOnFreshHome(t *testing.T) {
	f := newQueueFixture(t)
	path := filepath.Join(f.req.Machine.Home, ".clauderig", "queue-hooks.json")
	f.deps.routingPath = func() (string, error) { return path, nil }
	f.deps.resolve = func() (service.SyncRequest, error) {
		t.Fatal("fresh disable opened runtime")
		return service.SyncRequest{}, nil
	}
	out, err := f.execute(t.Context(), "disable-hooks")
	if err != nil || !strings.Contains(out, "not enabled") {
		t.Fatal(out, err)
	}
	if _, err := os.Lstat(filepath.Dir(path)); !os.IsNotExist(err) {
		t.Fatal("fresh disable created configuration state", err)
	}
}

func TestQueueHookRoutingDefaultProducerAndRecoveryUsePinnedInbox(t *testing.T) {
	for _, mode := range []string{"enabled", "disabled"} {
		t.Run(mode, func(t *testing.T) {
			f := newQueueFixture(t)
			path, _ := setupHookRouting(t, f)
			t.Setenv("HOME", f.req.Machine.Home)
			t.Setenv("USERPROFILE", f.req.Machine.Home)
			f.must(t, "init")
			custom := filepath.Join(t.TempDir(), "custom-inbox")
			f.must(t, "enable-hooks", "--inbox", custom)
			if mode == "disabled" {
				f.must(t, "disable-hooks")
			}
			saved, err := loadHookRouting(path)
			if err != nil {
				t.Fatal(err)
			}
			r := f.open(t)
			request, err := newQueueSubmission(r, "s", queue.Flush{Mode: queue.Normal}, false, f.deps.identity)
			if err != nil {
				t.Fatal(err)
			}
			if err := (hookInbox{dir: custom, save: durable.Write}).persist(t.Context(), hookInboxState{Version: 1, Scope: saved.Scope, Requests: []queueSubmission{request}}); err != nil {
				t.Fatal(err)
			}
			if _, err := f.execute(t.Context(), "disable-hooks"); err == nil || !strings.Contains(err.Error(), "inbox still") {
				t.Fatal("rollback ignored custom producer intent", err)
			}
			reads := f.reads
			f.must(t, "recover-hooks") // No --inbox: recover the pinned custom intent.
			if f.reads != reads {
				t.Fatal("recovery reread account")
			}
			source := filepath.Join(f.req.Machine.Home, ".claude", "projects", "-fixture", "s.jsonl")
			if _, _, err := executeHookAdmission(f, t.Context(), "", queueHookJSON(t, "Stop", "s", source)); err != nil {
				t.Fatal(err)
			}
			defaultInbox := filepath.Join(filepath.Dir(path), "hook-inbox")
			if _, err := os.Lstat(defaultInbox); !os.IsNotExist(err) {
				t.Fatal("default producer created an unpinned inbox", err)
			}
			state, err := (hookInbox{dir: custom}).load(saved.Scope)
			if err != nil || len(state.Requests) != 0 {
				t.Fatal(state, err)
			}
			work, err := r.Snapshot(t.Context())
			if err != nil || len(work) != 1 || len(work[0].Events) != 2 {
				t.Fatal(work, err)
			}
			if _, err := f.execute(t.Context(), "disable-hooks"); err == nil {
				t.Fatal("rollback ignored admitted work")
			}
			// Missing pinned state is corruption, not permission to initialize a different inbox.
			if err := os.Remove(filepath.Join(custom, "requests.json")); err != nil {
				t.Fatal(err)
			}
			if _, _, err := executeHookAdmission(f, t.Context(), "", queueHookJSON(t, "Stop", "s", source)); err == nil {
				t.Fatal("recreated missing pinned journal")
			}
			if _, err := f.execute(t.Context(), "recover-hooks"); err == nil {
				t.Fatal("recovery switched to default inbox")
			}
		})
	}
}

func TestQueueHookRoutingReenablePreservesRetainedState(t *testing.T) {
	for _, target := range []string{"same", "different"} {
		for _, problem := range []string{"missing-inbox", "corrupt-inbox", "inbox", "queue", "worker", "missing-runtime"} {
			t.Run(target+"/"+problem, func(t *testing.T) {
				f := newQueueFixture(t)
				path, _ := setupHookRouting(t, f)
				f.must(t, "init")
				f.must(t, "enable-hooks")
				f.must(t, "disable-hooks")
				old, err := loadHookRouting(path)
				if err != nil {
					t.Fatal(err)
				}
				descriptorBefore, err := os.ReadFile(path)
				if err != nil {
					t.Fatal(err)
				}
				oldRuntime := f.open(t)
				switch problem {
				case "missing-inbox":
					if err := os.RemoveAll(old.Inbox); err != nil {
						t.Fatal(err)
					}
				case "corrupt-inbox":
					if err := os.WriteFile(filepath.Join(old.Inbox, "requests.json"), []byte("{"), 0600); err != nil {
						t.Fatal(err)
					}
				case "inbox", "queue":
					request, err := newQueueSubmission(oldRuntime, "s", queue.Flush{Mode: queue.Normal}, false, f.deps.identity)
					if err != nil {
						t.Fatal(err)
					}
					if problem == "inbox" {
						err = (hookInbox{dir: old.Inbox, save: durable.Write}).persist(t.Context(), hookInboxState{Version: 1, Scope: old.Scope, Requests: []queueSubmission{request}})
					} else {
						_, err = oldRuntime.Enqueue(t.Context(), request.Identity, request.Request, request.At)
					}
					if err != nil {
						t.Fatal(err)
					}
				case "worker":
					_, release, err := storelock.Acquire(t.Context(), filepath.Join(f.dir, "queue", "worker"), 0)
					if err != nil {
						t.Fatal(err)
					}
					defer release()
				case "missing-runtime":
					if err := os.RemoveAll(f.dir); err != nil {
						t.Fatal(err)
					}
				}
				inboxBefore, inboxErr := os.ReadFile(filepath.Join(old.Inbox, "requests.json"))
				root := old.Inbox
				if target == "different" {
					f.dir = filepath.Join(t.TempDir(), "new-runtime")
					f.must(t, "init")
					root = filepath.Join(t.TempDir(), "new-inbox")
				}
				if _, err := f.execute(t.Context(), "enable-hooks", "--inbox", root); err == nil {
					t.Fatal("re-enable bypassed retained recovery", problem)
				}
				descriptorAfter, err := os.ReadFile(path)
				if err != nil || !bytes.Equal(descriptorBefore, descriptorAfter) {
					t.Fatal("re-enable replaced retained descriptor", err)
				}
				inboxAfter, afterErr := os.ReadFile(filepath.Join(old.Inbox, "requests.json"))
				if os.IsNotExist(afterErr) != os.IsNotExist(inboxErr) || !bytes.Equal(inboxBefore, inboxAfter) {
					t.Fatal("re-enable changed or recreated retained inbox", afterErr)
				}
				if target == "different" {
					if _, err := os.Lstat(root); !os.IsNotExist(err) {
						t.Fatal("created destination inbox before reconciliation", err)
					}
				}
				if problem == "queue" {
					work, err := oldRuntime.Snapshot(t.Context())
					if err != nil || len(work) != 1 || len(work[0].Events) != 1 {
						t.Fatal("lost retained queue work", work, err)
					}
				}
			})
		}
	}
}

func TestQueueHookRoutingRetargetAfterReconciliation(t *testing.T) {
	for _, failure := range []string{"none", "before", "after"} {
		t.Run(failure, func(t *testing.T) {
			f := newQueueFixture(t)
			path, _ := setupHookRouting(t, f)
			f.must(t, "init")
			f.must(t, "enable-hooks")
			f.must(t, "disable-hooks")
			old, err := loadHookRouting(path)
			if err != nil {
				t.Fatal(err)
			}
			oldRuntime := f.open(t)
			originalInbox, err := os.ReadFile(filepath.Join(old.Inbox, "requests.json"))
			if err != nil {
				t.Fatal(err)
			}
			f.dir = filepath.Join(t.TempDir(), "next-runtime")
			f.must(t, "init")
			nextScope := f.open(t).ScopeID()
			nextInbox := filepath.Join(t.TempDir(), "next-inbox")
			if failure != "none" {
				injected := errors.New("uncertain retained re-enable")
				f.deps.saveRouting = func(ctx context.Context, path string, s queueHookRouting) error {
					if failure == "after" {
						if err := saveHookRouting(ctx, path, s); err != nil {
							return err
						}
					}
					return injected
				}
				if _, err := f.execute(t.Context(), "enable-hooks", "--inbox", nextInbox); !errors.Is(err, injected) {
					t.Fatal(err)
				}
				current, err := loadHookRouting(path)
				if err != nil {
					t.Fatal(err)
				}
				if failure == "before" && (current.Enabled || current.Scope != old.Scope) {
					t.Fatal("lost old routing on failed replacement", current)
				}
				if failure == "after" && (!current.Enabled || current.Scope != nextScope) {
					t.Fatal("lost completed replacement", current)
				}
				f.deps.saveRouting = nil
			}
			f.must(t, "enable-hooks", "--inbox", nextInbox)
			current, err := loadHookRouting(path)
			if err != nil || !current.Enabled || current.Scope != nextScope || current.Inbox != nextInbox {
				t.Fatal(current, err)
			}
			preserved, err := os.ReadFile(filepath.Join(old.Inbox, "requests.json"))
			if err != nil || !bytes.Equal(originalInbox, preserved) {
				t.Fatal("retarget changed retained producer state", err)
			}
			work, err := oldRuntime.Snapshot(t.Context())
			if err != nil || len(work) != 0 {
				t.Fatal("retarget removed or changed retained queue", work, err)
			}
			f.must(t, "disable-hooks")
		})
	}
}
