package dotnet

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rigsmith/rigsmith/core/plugin"
	"github.com/rigsmith/rigsmith/core/walkutil"
)

// overlayFile is where MSBuild's walk-up will find the redirects: the highest
// directory every project shares.
const overlayFile = "Directory.Build.targets"

// overlayMarker identifies a file rig generated, so a rewrite replaces its own
// work and refuses to clobber one somebody wrote by hand.
const overlayMarker = "<!-- generated by rig: package references redirected to sources in this tree -->"

// LocalOverlay writes a Directory.Build.targets that swaps PackageReferences for
// ProjectReferences, and reports what would stop it applying.
//
// The reporting half matters more than the writing half. Every way this goes
// wrong is silent: MSBuild resolves the registry copy, the build succeeds, and
// nothing says which one it used.
func (a *Adapter) LocalOverlay(ctx context.Context, req plugin.LocalOverlayRequest) (plugin.LocalOverlayResponse, error) {
	resp := plugin.LocalOverlayResponse{}
	if len(req.Redirects) == 0 {
		resp.Skipped = true
		resp.Reason = "nothing to redirect"
		// An overlay left over from members that have since gone would keep
		// pointing packages at projects that are no longer there — a build
		// error at best, and the wrong sources at worst. Only rig's own file is
		// removed; one somebody wrote stays, whatever it says.
		if req.Write {
			removed, err := removeGenerated(filepath.Join(req.Root, overlayFile), overlayMarker, overlayFile)
			resp.Removed = removed
			return resp, err
		}
		// An overlay rig wrote for members that have since gone still swaps
		// packages for projects at paths that may have left; a check says
		// so rather than calling an ecosystem with nothing to redirect
		// healthy.
		if !req.Write {
			existing, err := os.ReadFile(filepath.Join(req.Root, overlayFile))
			switch {
			case errors.Is(err, fs.ErrNotExist):
			case err != nil:
				// Present but unreadable is not healthy, whether or not
				// anything crosses: MSBuild cannot use it either.
				resp.Skipped = false
				resp.Problems = append(resp.Problems, plugin.OverlayProblem{
					Path:    overlayFile,
					Message: "cannot be read (" + err.Error() + ") — MSBuild cannot use it either; make the file readable",
				})
			case strings.Contains(string(existing), overlayMarker):
				resp.Skipped = false
				resp.Problems = append(resp.Problems, plugin.OverlayProblem{
					Path:    overlayFile,
					Message: "left over — no package reference crosses between members any more, so it only redirects to paths that may have left; delete it",
				})
			}
		}
		return resp, nil
	}

	problems, fixed := overlayProblems(req)
	resp.Problems = problems
	resp.Fixed = fixed

	body := renderOverlay(req.Redirects)
	resp.Files = map[string]string{overlayFile: body}
	if !req.Write {
		// A missing overlay, and an overlay rig wrote earlier that no longer
		// matches what it would write now — a member added since, or a
		// release that changed the template — are equally silent: the build
		// succeeds against the registry either way. So a check says so.
		// Staleness is judged with line endings normalised: a checkout with
		// autocrlf hands the same file back with CRLF, and that is not it.
		existing, err := os.ReadFile(filepath.Join(req.Root, overlayFile))
		switch {
		case errors.Is(err, fs.ErrNotExist):
			resp.Problems = append(resp.Problems, plugin.OverlayProblem{
				Path:    overlayFile,
				Message: "not written — every project here still resolves these packages from the registry; run `rig stack wire`",
				Fixable: true,
			})
		case err != nil:
			// Present but unreadable is not healthy: MSBuild cannot use it
			// either, and rig cannot say what it holds.
			resp.Problems = append(resp.Problems, plugin.OverlayProblem{
				Path:    overlayFile,
				Message: "cannot be read (" + err.Error() + ") — MSBuild cannot use it either; make the file readable",
			})
		case strings.Contains(string(existing), overlayMarker) && crlfToLF(string(existing)) != crlfToLF(body):
			resp.Problems = append(resp.Problems, plugin.OverlayProblem{
				Path:    overlayFile,
				Message: "out of date — it differs from what the current members and rig would write; re-run `rig stack wire`, which rewrites the file whole (if you extended it by hand, drop the marker line to make it yours, and keep it current yourself)",
				Fixable: true,
			})
		}
		return resp, nil
	}

	dest := filepath.Join(req.Root, overlayFile)
	if existing, err := os.ReadFile(dest); err == nil && !strings.Contains(string(existing), overlayMarker) {
		// Not "%s already exists…": the error renderer sentence-cases the first
		// word, and a filename is the one thing that must not be reshaped.
		return resp, fmt.Errorf("there is already a %s here that rig did not write — move it aside, or merge the redirects into it by hand", overlayFile)
	}
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return resp, err
	}
	return resp, nil
}

// overlayProblems reports what would keep the overlay from taking effect. It
// reads files rather than running MSBuild: an evaluation is a better check but
// needs the SDK, and the failures worth catching here are structural.
func overlayProblems(req plugin.LocalOverlayRequest) ([]plugin.OverlayProblem, []string) {
	var out []plugin.OverlayProblem
	var fixed []string

	// A build file between the root and any project ends MSBuild's search there,
	// and every project beneath it keeps resolving packages from the registry.
	// This is the one that costs people an afternoon, because the build succeeds.
	//
	// The whole tree is scanned rather than the paths being redirected: the file
	// that shadows the overlay sits above the *consumers*, and a redirect only
	// says where a package is produced. Looking only along those paths misses
	// exactly the case worth catching.
	_ = walkutil.Walk(req.Root, func(path string, d fs.DirEntry) error {
		if d.IsDir() || filepath.Base(path) != overlayFile {
			return nil
		}
		rel, err := filepath.Rel(req.Root, path)
		if err != nil || rel == overlayFile {
			return nil // the overlay itself
		}
		rel = filepath.ToSlash(rel)
		data, err := os.ReadFile(path)
		if err != nil || continuesWalkUp(string(data)) {
			return nil
		}
		// Patching this means editing a file inside somebody's project, which is
		// a commit to that repository. Only where the caller said it is welcome.
		allowed := underAny(rel, req.Writable)
		if allowed && req.Write {
			if patched, ok := patchWalkUp(string(data)); ok {
				if err := os.WriteFile(path, []byte(patched), 0o644); err == nil {
					fixed = append(fixed, rel)
					return nil
				}
			}
		}
		out = append(out, plugin.OverlayProblem{
			Path: rel,
			Message: "ends MSBuild's search for " + overlayFile +
				", so projects under it keep resolving packages from the registry — import the file above it",
			Fixable: allowed,
		})
		return nil
	})

	// A redirect naming a package nothing references is almost always a typo in
	// the identity, and produces an overlay that is valid and does nothing.
	for _, r := range req.Redirects {
		if _, err := os.Stat(filepath.Join(req.Root, r.Path)); err != nil {
			out = append(out, plugin.OverlayProblem{
				Path:    r.Path,
				Message: "no project here to redirect " + r.Package + " to",
			})
		}
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	sort.Strings(fixed)
	return out, fixed
}

// underAny reports whether rel sits inside one of the permitted directories.
func underAny(rel string, dirs []string) bool {
	for _, d := range dirs {
		d = filepath.ToSlash(strings.TrimSuffix(d, "/"))
		if d == "." || rel == d || strings.HasPrefix(rel, d+"/") {
			return true
		}
	}
	return false
}

// patchWalkUp inserts the import that continues MSBuild's search, right after
// the opening Project element. Reports false when there is no such element to
// insert after, rather than writing something that will not parse.
//
// The path is resolved into a property first: a Condition is itself
// single-quoted, and the quotes this function needs around its arguments cannot
// appear inside one (MSB4092).
func patchWalkUp(body string) (string, bool) {
	open := strings.Index(body, "<Project")
	if open < 0 {
		return "", false
	}
	end := strings.Index(body[open:], ">")
	if end < 0 {
		return "", false
	}
	at := open + end + 1
	const patch = `

  <!-- Added by rig. MSBuild stops at the first Directory.Build.targets it finds
       walking up, so without this every project below here would keep resolving
       packages from the registry even inside a workspace that redirects them —
       and the build would succeed, saying nothing. No-op outside one, where
       there is nothing above. -->
  <PropertyGroup>
    <StackParentTargets>$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets', '$(MSBuildThisFileDirectory)../'))</StackParentTargets>
  </PropertyGroup>
  <Import Project="$(StackParentTargets)" Condition="'$(StackParentTargets)' != ''" />
`
	return body[:at] + patch + body[at:], true
}

// continuesWalkUp reports whether a Directory.Build.targets imports the one
// above it, which is what stops it hiding an outer overlay.
//
// Comments are stripped first, and an actual <Import> is required. Looking for
// the function name alone is not enough: it is usually resolved into a property
// on the line above, so a commented-out import leaves the name in the file and
// the check passes while the build silently does not.
func continuesWalkUp(body string) bool {
	body = stripXMLComments(body)
	if !strings.Contains(body, "GetPathOfFileAbove") {
		return false
	}
	return strings.Contains(body, "<Import")
}

// stripXMLComments removes <!-- ... --> so a commented-out element does not read
// as a live one. An unterminated comment swallows the rest, which is what the
// XML parser would do too.
func stripXMLComments(body string) string {
	var b strings.Builder
	for {
		i := strings.Index(body, "<!--")
		if i < 0 {
			b.WriteString(body)
			return b.String()
		}
		b.WriteString(body[:i])
		rest := body[i+4:]
		j := strings.Index(rest, "-->")
		if j < 0 {
			return b.String()
		}
		body = rest[j+3:]
	}
}

// renderOverlay builds the file. Each package is named once, and selected by
// set arithmetic rather than a condition per redirect: Exclude matches on
// identity, so subtracting the sources a project does not reference leaves
// exactly the ones it does. A hand-written condition tends to be written against
// %(Filename), which MSBuild splits at the last dot — so a redirect meant for
// one package silently matches a differently-named sibling.
func renderOverlay(redirects []plugin.Redirect) string {
	sorted := append([]plugin.Redirect(nil), redirects...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Package < sorted[j].Package })

	var b strings.Builder
	b.WriteString("<Project>\n\n  ")
	b.WriteString(overlayMarker)
	b.WriteString("\n\n  <ItemGroup>\n")
	for _, r := range sorted {
		fmt.Fprintf(&b, "    <StackSource Include=%q Path=%q />\n", r.Package, filepath.ToSlash(r.Path))
	}
	b.WriteString("  </ItemGroup>\n\n")
	b.WriteString(`  <ItemGroup Condition="'$(UseStackSources)' != 'false'">
    <_StackAbsent  Include="@(StackSource)" Exclude="@(PackageReference)" />
    <_StackPresent Include="@(StackSource)" Exclude="@(_StackAbsent)" />
    <ProjectReference Include="@(_StackPresent->'$(MSBuildThisFileDirectory)%(Path)')" />
    <PackageReference Remove="@(StackSource)" />
  </ItemGroup>

`)
	b.WriteString(overlayNoRefAssemblies)
	b.WriteString("\n</Project>\n")
	return b.String()
}

// removeGenerated deletes path when it carries marker and reports the removal
// under rel. A missing file, or one without the marker, removes nothing. A
// file that carries the marker and cannot be read or removed is an error: a
// stale overlay left standing silently is the failure this exists to prevent.
func removeGenerated(path, marker, rel string) ([]string, error) {
	body, err := os.ReadFile(path)
	if errors.Is(err, fs.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("reading %s: %w", rel, err)
	}
	if !strings.Contains(string(body), marker) {
		return nil, nil
	}
	if err := os.Remove(path); err != nil {
		return nil, fmt.Errorf("removing stale %s: %w", rel, err)
	}
	return []string{rel}, nil
}

// overlayNoRefAssemblies is the part of the overlay that keeps a swap from
// breaking anything that reads a dependency's internals.
//
// A package with no separate ref/<TFM> asset — most of them — hands the
// consumer its implementation assembly, and a publicizer (IgnoresAccessChecksTo
// and friends) rewrites what the compiler sees. A project reference is different:
// the SDK also produces a *reference* assembly, internals stripped, and hands
// the consumer that one — so the publicized copy is built and then ignored,
// and every internal comes back as CS0122, on members that did not change.
// Nothing about the code, the versions, or InternalsVisibleTo is involved,
// which is why it reads like API drift and costs an afternoon.
//
// Every project under the overlay gets the property, not only the redirected
// ones. Matching the current project against the redirect paths would have to
// be done in a condition, with separators and casing that differ across
// platforms, and a match that fails does so silently — the very thing this
// overlay exists to prevent. Reference assemblies are a build-time
// optimisation, and inside a stackspace, where everything rebuilds together,
// the cost of not having them is small. The escape hatch is the same one that
// restores the against-real-packages build.
const overlayNoRefAssemblies = `  <!-- A project reference hands consumers a reference assembly, internals
       stripped, that a publicizer (IgnoresAccessChecksTo) never rewrote — so a
       swap above would turn every internal it exposes into CS0122. A package
       without a separate ref/<TFM> asset hands consumers its implementation
       assembly instead, which is why the same code compiled before. -->
  <PropertyGroup Condition="'$(UseStackSources)' != 'false'">
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
`

// crlfToLF normalises line endings for comparisons that must not mistake a
// checkout's autocrlf conversion for a change.
func crlfToLF(s string) string { return strings.ReplaceAll(s, "\r\n", "\n") }
