package dotnet

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/rigsmith/rigsmith/core/plugin"
	"github.com/rigsmith/rigsmith/core/walkutil"
)

// overlayFile is where MSBuild's walk-up will find the redirects: the highest
// directory every project shares.
const overlayFile = "Directory.Build.targets"

// overlayMarker identifies a file rig generated, so a rewrite replaces its own
// work and refuses to clobber one somebody wrote by hand.
const overlayMarker = "<!-- generated by rig: package references redirected to sources in this tree -->"

// LocalOverlay writes a Directory.Build.targets that swaps PackageReferences for
// ProjectReferences, and reports what would stop it applying.
//
// The reporting half matters more than the writing half. Every way this goes
// wrong is silent: MSBuild resolves the registry copy, the build succeeds, and
// nothing says which one it used.
func (a *Adapter) LocalOverlay(ctx context.Context, req plugin.LocalOverlayRequest) (plugin.LocalOverlayResponse, error) {
	resp := plugin.LocalOverlayResponse{}
	if len(req.Redirects) == 0 {
		resp.Skipped = true
		resp.Reason = "nothing to redirect"
		return resp, nil
	}

	for _, p := range overlayProblems(req) {
		resp.Problems = append(resp.Problems, p)
	}

	body := renderOverlay(req.Redirects)
	resp.Files = map[string]string{overlayFile: body}
	if !req.Write {
		return resp, nil
	}

	dest := filepath.Join(req.Root, overlayFile)
	if existing, err := os.ReadFile(dest); err == nil && !strings.Contains(string(existing), overlayMarker) {
		// Not "%s already exists…": the error renderer sentence-cases the first
		// word, and a filename is the one thing that must not be reshaped.
		return resp, fmt.Errorf("there is already a %s here that rig did not write — move it aside, or merge the redirects into it by hand", overlayFile)
	}
	if err := os.WriteFile(dest, []byte(body), 0o644); err != nil {
		return resp, err
	}
	return resp, nil
}

// overlayProblems reports what would keep the overlay from taking effect. It
// reads files rather than running MSBuild: an evaluation is a better check but
// needs the SDK, and the failures worth catching here are structural.
func overlayProblems(req plugin.LocalOverlayRequest) []plugin.OverlayProblem {
	var out []plugin.OverlayProblem

	// A build file between the root and any project ends MSBuild's search there,
	// and every project beneath it keeps resolving packages from the registry.
	// This is the one that costs people an afternoon, because the build succeeds.
	//
	// The whole tree is scanned rather than the paths being redirected: the file
	// that shadows the overlay sits above the *consumers*, and a redirect only
	// says where a package is produced. Looking only along those paths misses
	// exactly the case worth catching.
	_ = walkutil.Walk(req.Root, func(path string, d fs.DirEntry) error {
		if d.IsDir() || filepath.Base(path) != overlayFile {
			return nil
		}
		rel, err := filepath.Rel(req.Root, path)
		if err != nil || rel == overlayFile {
			return nil // the overlay itself
		}
		data, err := os.ReadFile(path)
		if err != nil || continuesWalkUp(string(data)) {
			return nil
		}
		out = append(out, plugin.OverlayProblem{
			Path: filepath.ToSlash(rel),
			Message: "ends MSBuild's search for " + overlayFile +
				", so projects under it keep resolving packages from the registry — import the file above it",
			Fixable: false,
		})
		return nil
	})

	// A redirect naming a package nothing references is almost always a typo in
	// the identity, and produces an overlay that is valid and does nothing.
	for _, r := range req.Redirects {
		if _, err := os.Stat(filepath.Join(req.Root, r.Path)); err != nil {
			out = append(out, plugin.OverlayProblem{
				Path:    r.Path,
				Message: "no project here to redirect " + r.Package + " to",
			})
		}
	}

	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out
}

// continuesWalkUp reports whether a Directory.Build.targets imports the one
// above it, which is what stops it hiding an outer overlay.
//
// Comments are stripped first, and an actual <Import> is required. Looking for
// the function name alone is not enough: it is usually resolved into a property
// on the line above, so a commented-out import leaves the name in the file and
// the check passes while the build silently does not.
func continuesWalkUp(body string) bool {
	body = stripXMLComments(body)
	if !strings.Contains(body, "GetPathOfFileAbove") {
		return false
	}
	return strings.Contains(body, "<Import")
}

// stripXMLComments removes <!-- ... --> so a commented-out element does not read
// as a live one. An unterminated comment swallows the rest, which is what the
// XML parser would do too.
func stripXMLComments(body string) string {
	var b strings.Builder
	for {
		i := strings.Index(body, "<!--")
		if i < 0 {
			b.WriteString(body)
			return b.String()
		}
		b.WriteString(body[:i])
		rest := body[i+4:]
		j := strings.Index(rest, "-->")
		if j < 0 {
			return b.String()
		}
		body = rest[j+3:]
	}
}

// renderOverlay builds the file. Each package is named once, and selected by
// set arithmetic rather than a condition per redirect: Exclude matches on
// identity, so subtracting the sources a project does not reference leaves
// exactly the ones it does. A hand-written condition tends to be written against
// %(Filename), which MSBuild splits at the last dot — so a redirect meant for
// one package silently matches a differently-named sibling.
func renderOverlay(redirects []plugin.Redirect) string {
	sorted := append([]plugin.Redirect(nil), redirects...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Package < sorted[j].Package })

	var b strings.Builder
	b.WriteString("<Project>\n\n  ")
	b.WriteString(overlayMarker)
	b.WriteString("\n\n  <ItemGroup>\n")
	for _, r := range sorted {
		fmt.Fprintf(&b, "    <StackSource Include=%q Path=%q />\n", r.Package, filepath.ToSlash(r.Path))
	}
	b.WriteString("  </ItemGroup>\n\n")
	b.WriteString(`  <ItemGroup Condition="'$(UseStackSources)' != 'false'">
    <_StackAbsent  Include="@(StackSource)" Exclude="@(PackageReference)" />
    <_StackPresent Include="@(StackSource)" Exclude="@(_StackAbsent)" />
    <ProjectReference Include="@(_StackPresent->'$(MSBuildThisFileDirectory)%(Path)')" />
    <PackageReference Remove="@(StackSource)" />
  </ItemGroup>

</Project>
`)
	return b.String()
}
