package dotnet

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/rigsmith/rigsmith/core/plugin"
)

func TestLocalOverlay(t *testing.T) {
	ctx := context.Background()
	a := New()

	newRoot := func(t *testing.T) string {
		t.Helper()
		root := t.TempDir()
		writeFile(t, filepath.Join(root, "lib/src/Pty.Core/Pty.Core.csproj"), "<Project/>")
		writeFile(t, filepath.Join(root, "app/src/App/App.csproj"), "<Project/>")
		return root
	}
	redirects := []plugin.Redirect{{Package: "Pty.Core", Path: "lib/src/Pty.Core/Pty.Core.csproj"}}

	t.Run("nothing to redirect is skipped, not an empty file", func(t *testing.T) {
		got, err := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{Root: newRoot(t)})
		if err != nil {
			t.Fatal(err)
		}
		if !got.Skipped || len(got.Files) != 0 {
			t.Fatalf("%+v, want skipped with no files", got)
		}
	})

	t.Run("describes without writing", func(t *testing.T) {
		root := newRoot(t)
		got, err := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{Root: root, Redirects: redirects})
		if err != nil {
			t.Fatal(err)
		}
		if body := got.Files[overlayFile]; !strings.Contains(body, `Include="Pty.Core"`) {
			t.Fatalf("overlay does not name the package:\n%s", body)
		}
		if _, err := os.Stat(filepath.Join(root, overlayFile)); !os.IsNotExist(err) {
			t.Fatal("wrote a file without being asked to")
		}
	})

	t.Run("names each package once", func(t *testing.T) {
		// The point of the set-arithmetic form: no condition per redirect, so
		// nothing is written against %(Filename), which MSBuild splits at the
		// last dot and would match a differently-named sibling.
		got, _ := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{
			Root: newRoot(t),
			Redirects: []plugin.Redirect{
				{Package: "Pty.Core", Path: "lib/src/Pty.Core/Pty.Core.csproj"},
				{Package: "Pty.Core.Native", Path: "lib/src/Pty.Core/Pty.Core.csproj"},
			},
		})
		body := got.Files[overlayFile]
		if n := strings.Count(body, "Pty.Core.Native"); n != 1 {
			t.Errorf("Pty.Core.Native appears %d times, want once", n)
		}
		if strings.Contains(body, "Filename") {
			t.Error("overlay matches on Filename, which splits at the last dot")
		}
	})

	t.Run("a nearer build file is reported, because it silently wins", func(t *testing.T) {
		root := newRoot(t)
		writeFile(t, filepath.Join(root, "lib", overlayFile), "<Project>\n</Project>\n")
		got, err := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{Root: root, Redirects: redirects})
		if err != nil {
			t.Fatal(err)
		}
		var found bool
		for _, p := range got.Problems {
			if strings.HasPrefix(p.Path, "lib") && strings.Contains(p.Message, "ends MSBuild's search") {
				found = true
			}
		}
		if !found {
			t.Fatalf("shadowing file not reported: %+v", got.Problems)
		}
	})

	t.Run("a nearer build file that continues the walk-up is fine", func(t *testing.T) {
		root := newRoot(t)
		writeFile(t, filepath.Join(root, "lib", overlayFile),
			"<Project>\n<Import Project=\"$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets','$(MSBuildThisFileDirectory)../'))\" />\n</Project>\n")
		got, _ := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{Root: root, Redirects: redirects})
		for _, p := range got.Problems {
			if strings.Contains(p.Message, "ends MSBuild's search") {
				t.Fatalf("reported a file that imports the one above it: %+v", p)
			}
		}
	})

	t.Run("a redirect pointing nowhere is reported", func(t *testing.T) {
		got, _ := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{
			Root:      newRoot(t),
			Redirects: []plugin.Redirect{{Package: "Typo.Core", Path: "lib/src/Nope/Nope.csproj"}},
		})
		if len(got.Problems) == 0 || !strings.Contains(got.Problems[0].Message, "Typo.Core") {
			t.Fatalf("missing redirect not reported: %+v", got.Problems)
		}
	})

	t.Run("writing, then rewriting its own file", func(t *testing.T) {
		root := newRoot(t)
		if _, err := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{Root: root, Redirects: redirects, Write: true}); err != nil {
			t.Fatal(err)
		}
		body, err := os.ReadFile(filepath.Join(root, overlayFile))
		if err != nil {
			t.Fatal(err)
		}
		if !strings.Contains(string(body), overlayMarker) {
			t.Fatal("written file carries no marker, so a rewrite could not tell it apart from a hand-written one")
		}
		if _, err := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{Root: root, Redirects: redirects, Write: true}); err != nil {
			t.Fatalf("refused to rewrite its own file: %v", err)
		}
	})

	t.Run("refuses to clobber a file it did not write", func(t *testing.T) {
		root := newRoot(t)
		writeFile(t, filepath.Join(root, overlayFile), "<Project>\n  <!-- mine -->\n</Project>\n")
		_, err := a.LocalOverlay(ctx, plugin.LocalOverlayRequest{Root: root, Redirects: redirects, Write: true})
		if err == nil || !strings.Contains(err.Error(), "not generated by rig") {
			t.Fatalf("got %v, want a refusal naming the existing file", err)
		}
		body, _ := os.ReadFile(filepath.Join(root, overlayFile))
		if !strings.Contains(string(body), "mine") {
			t.Fatal("clobbered it anyway")
		}
	})
}

// TestLocalOverlayShadowAboveConsumers is the case a redirect-path scan misses:
// the file that shadows the overlay sits above the *consumer*, and a redirect
// only says where a package is produced.
func TestLocalOverlayShadowAboveConsumers(t *testing.T) {
	ctx := context.Background()
	root := t.TempDir()
	writeFile(t, filepath.Join(root, "lib/src/Pty.Core/Pty.Core.csproj"), "<Project/>")
	writeFile(t, filepath.Join(root, "app/src/App/App.csproj"), "<Project/>")
	// Nothing under lib/ is wrong; app/ is where the consumer lives.
	writeFile(t, filepath.Join(root, "app", overlayFile), "<Project>\n  <!-- unrelated build tweak -->\n</Project>\n")

	got, err := New().LocalOverlay(ctx, plugin.LocalOverlayRequest{
		Root:      root,
		Redirects: []plugin.Redirect{{Package: "Pty.Core", Path: "lib/src/Pty.Core/Pty.Core.csproj"}},
	})
	if err != nil {
		t.Fatal(err)
	}
	var found bool
	for _, p := range got.Problems {
		if strings.HasPrefix(p.Path, "app") {
			found = true
		}
	}
	if !found {
		t.Fatalf("shadowing file above the consumer not reported: %+v", got.Problems)
	}
}

func TestContinuesWalkUp(t *testing.T) {
	live := "<Project>\n<PropertyGroup><P>$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets','x'))</P></PropertyGroup>\n<Import Project=\"$(P)\" />\n</Project>"
	if !continuesWalkUp(live) {
		t.Error("a real import was not recognised")
	}
	// The trap: the function name is resolved into a property on the line above,
	// so a commented-out import leaves the name in the file. Matching the name
	// alone reports this as fine while the build silently is not.
	commented := "<Project>\n<PropertyGroup><P>$([MSBuild]::GetPathOfFileAbove('Directory.Build.targets','x'))</P></PropertyGroup>\n<!-- <Import Project=\"$(P)\" /> -->\n</Project>"
	if continuesWalkUp(commented) {
		t.Error("a commented-out import was treated as live")
	}
	if continuesWalkUp("<Project>\n</Project>") {
		t.Error("a file with no import at all was treated as continuing the walk-up")
	}
}
