package gomod

import (
	"context"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/rigsmith/rigsmith/core/plugin"
	"github.com/rigsmith/rigsmith/core/walkutil"
)

// workFile is where Go looks to resolve modules from the tree rather than from
// the proxy.
const workFile = "go.work"

// workMarker identifies a file rig generated, so a rewrite replaces its own work
// and refuses to clobber one somebody wrote by hand.
const workMarker = "// generated by rig: modules below resolve from this tree, not the proxy"

// LocalOverlay writes a go.work covering every module in the tree.
//
// Go does not resolve a sibling module by being next to it: a require on a
// module path goes to the proxy however close the sources are. A go.work listing
// both ends is what makes the local copy win, and it is a file Go already
// understands rather than anything rig invents.
//
// Unlike the .NET overlay this is not a per-package redirect — go.work lists
// module directories, not dependencies — so the redirects only decide *whether*
// there is anything to do. The listing is discovered here, because which
// directories hold modules is a question about Go and not about the caller.
func (a *Adapter) LocalOverlay(ctx context.Context, req plugin.LocalOverlayRequest) (plugin.LocalOverlayResponse, error) {
	resp := plugin.LocalOverlayResponse{}
	if len(req.Redirects) == 0 {
		resp.Skipped = true
		resp.Reason = "no module in this tree is required by another"
		// A generated go.work that still lists a directory which has left the
		// tree fails every go command here, so a Write with nothing to redirect
		// takes rig's own file away. A hand-written one is never touched.
		if req.Write {
			dest := filepath.Join(req.Root, workFile)
			if body, err := os.ReadFile(dest); err == nil && strings.Contains(string(body), workMarker) {
				if os.Remove(dest) == nil {
					resp.Removed = []string{workFile}
				}
			}
		}
		return resp, nil
	}

	mods, goVersion, err := moduleDirs(req.Root)
	if err != nil {
		return resp, err
	}
	if len(mods) < 2 {
		resp.Skipped = true
		resp.Reason = "only one module here, so nothing resolves through the proxy"
		return resp, nil
	}

	dest := filepath.Join(req.Root, workFile)
	existing, readErr := os.ReadFile(dest)
	generated := readErr == nil && strings.Contains(string(existing), workMarker)

	// A go.work somebody else wrote is authoritative, and rewriting it would
	// discard whatever else it says. Report what is missing from it instead.
	if readErr == nil && !generated {
		for _, m := range mods {
			if !strings.Contains(string(existing), "./"+m) {
				resp.Problems = append(resp.Problems, plugin.OverlayProblem{
					Path:    workFile,
					Message: m + " is not in this go.work, so a require on it is fetched from the proxy instead of read from the tree",
				})
			}
		}
		if req.Write && len(resp.Problems) > 0 {
			return resp, fmt.Errorf("there is already a %s here that rig did not write — add the missing modules to it by hand", workFile)
		}
		return resp, nil
	}

	// An existing directive wins; otherwise take the highest the modules ask
	// for. Omitting it is not an option: go.work then defaults to 1.18, and
	// every module wanting more than that fails to load.
	if v := goDirective(string(existing)); v != "" {
		goVersion = v
	}
	body := renderWork(goVersion, mods)
	resp.Files = map[string]string{workFile: body}
	if !req.Write {
		return resp, nil
	}
	return resp, os.WriteFile(dest, []byte(body), 0o644)
}

// moduleDirs lists every directory under root holding a go.mod, relative to root
// and slash-separated, sorted so the file is stable across runs. It also returns
// the highest language version any of them declares, which is what the go.work
// has to say: a workspace declaring less than a module it lists cannot load it.
func moduleDirs(root string) ([]string, string, error) {
	var out []string
	var highest string
	err := walkutil.Walk(root, func(path string, d fs.DirEntry) error {
		if d.IsDir() || filepath.Base(path) != "go.mod" {
			return nil
		}
		rel, err := filepath.Rel(root, filepath.Dir(path))
		if err != nil {
			return nil
		}
		out = append(out, filepath.ToSlash(rel))
		if body, err := os.ReadFile(path); err == nil {
			if v := goDirective(string(body)); higherGoVersion(v, highest) {
				highest = v
			}
		}
		return nil
	})
	if err != nil {
		return nil, "", err
	}
	sort.Strings(out)
	return out, highest, nil
}

// higherGoVersion reports whether a is a later language version than b, treating
// an empty b as lower than anything. Compared field by field as numbers, so 1.9
// does not outrank 1.24 the way a string comparison would.
func higherGoVersion(a, b string) bool {
	if a == "" {
		return false
	}
	if b == "" {
		return true
	}
	af, bf := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(af) && i < len(bf); i++ {
		x, errA := strconv.Atoi(af[i])
		y, errB := strconv.Atoi(bf[i])
		if errA != nil || errB != nil {
			return a > b
		}
		if x != y {
			return x > y
		}
	}
	return len(af) > len(bf)
}

// goDirective is the language version an existing go.work declares, so a rewrite
// keeps it. Empty when there is nothing to keep; the caller omits the line
// rather than guessing a version, which go fills in on first use.
func goDirective(existing string) string {
	for _, line := range strings.Split(existing, "\n") {
		if v, ok := strings.CutPrefix(strings.TrimSpace(line), "go "); ok {
			return strings.TrimSpace(v)
		}
	}
	return ""
}

func renderWork(goVersion string, mods []string) string {
	var b strings.Builder
	b.WriteString(workMarker)
	b.WriteString("\n\n")
	if goVersion != "" {
		fmt.Fprintf(&b, "go %s\n\n", goVersion)
	}
	b.WriteString("use (\n")
	for _, m := range mods {
		if m == "." {
			b.WriteString("\t.\n")
			continue
		}
		fmt.Fprintf(&b, "\t./%s\n", m)
	}
	b.WriteString(")\n")
	return b.String()
}
